### ISSUE TITLE
forget comma (,)  in client - main.lua

### ISSUE THREAD

**Issue by FuTuRNeT** [ESX-Org/esx_policejob#101]
Hi, 
i think your are forget the comma ine this line in your script in value = 'fine'} 

{label = _U('fine'),			value = 'fine'}

**Comment by HumanTree92** [comment]
Your not supposed to put a comment there. I would close this as you have no clue on what your talking about.

**Comment by ElPumpo** [comment]
Not the first time people inspect the code by just reading it. It is standard lua code and works just fine
