### ISSUE TITLE
Impound vehicle changes state on DB

### ISSUE THREAD

**Issue by Angelsking** [ESX-Org/esx_policejob#104]
Anyone able to help with this I know the state of a vehicle needs to be set to "0" in order for it to be impounded and wanted to know if you could help out with adding this into the script I cant seem to get it to work. 

Thanks

**Comment by ElPumpo** [comment]
This is not an issue with the script. Ask for help somewhere else, e.g the ESX discord.

**Comment by Angelsking** [comment]
yea see I ask for help somewhere else and because the player base for this just want to charge each other for a line of fucking code. So there is no use is asking on there it will get ignored or someone will ask for money so.......

**Comment by ElPumpo** [comment]
You open ISSUES here on github, it id **NOT** the place to ask for help, understand?!

**Comment by Angelsking** [comment]
No I don't write LUA is a useless language... your one to talk about getting mad but you are an example of your own shit player base. You don't offer any assistance to questions you just get pissed when someone asks for help. Maybe you wouldent have these issues if you actually supported your work assisted others in improving it rather then acting like the child you are

**Comment by ElPumpo** [comment]
> No I don't write LUA is a useless language

you're useless, now fuck off
