### ISSUE TITLE
Improve car spawn system

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_policejob#109]
- [x] add additional car spawn behind mission row ae13da8170eea830d0d53f9e332f1cbeb07862cf
- [x] check for existing cars to fix cars spawning on top of each other
    - [x] add multiple spawnpoints for every car spawn zone

**Comment by LuaDeldu** [comment]
In oder to save you some seconds, maybe ~

> check for existing car to fix cars spawning on top of each other

```lua
local vehicleNearPoint = GetClosestVehicle(vehicles[partNum].SpawnPoint.x, vehicles[partNum].SpawnPoint.y, vehicles[partNum].SpawnPoint.z, 3.0, 0, 71)
if not DoesEntityExist(vehicleNearPoint) and not IsAnyVehicleNearPoint(vehicles[partNum].SpawnPoint.x, vehicles[partNum].SpawnPoint.y, vehicles[partNum].SpawnPoint.z, 6.0) then
	ESX.Game.SpawnVehicle(model, {
		x = vehicles[partNum].SpawnPoint.x,
		y = vehicles[partNum].SpawnPoint.y,
		z = vehicles[partNum].SpawnPoint.z
	}, vehicles[partNum].Heading, function(vehicle)
		TaskWarpPedIntoVehicle(playerPed,  vehicle,  -1)
		SetVehicleMaxMods(vehicle)
	end)
else
	ESX.ShowNotification(_U('vehicle_block_exit'))
end		
```

**Comment by ElPumpo** [comment]
Let's make it a seperate function returning a boolean. `IsSpawnpointClear(coords)`

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/5e6714a3239776002f4b5cb383fc520e2bf2bd9c adds `ESX.Game.IsSpawnPointClear(coords, radius)`

**Comment by ElPumpo** [comment]
Working on it today, expect it to be updated!
