### ISSUE TITLE
Vehicle Information not returning anything

### ISSUE THREAD

**Issue by wes187inc** [ESX-Org/esx_policejob#116]
It won't return a UNKNOWN message or any information based off vehicle plates. Even tried to run a plate that I can see in the database but it doesn't show anything.

Is this the right set up for the owned_vehicles in the database or is it a police job issue.
![image](https://user-images.githubusercontent.com/29553654/42070712-9d808d10-7b0c-11e8-969e-9f4eb6746709.png)

**Comment by ElPumpo** [comment]
Update esx. New function used

**Comment by wes187inc** [comment]
Updated esx, getting this
`[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE plate = @plate {@plate=64FZP241}": Unknown column 'plate' in 'where clause'`

Seems it is trying to pull they plate from a column that esx_vehicleshop doesn't use. They just throw the vehicle plate number in with all the mods ids.
`ESX.RegisterServerCallback('esx_policejob:getVehicleFromPlate', function(source, cb, plate)
    MySQL.Async.fetchAll(
        'SELECT * FROM owned_vehicles WHERE plate = @plate', 
        {
            ['@plate'] = plate
        },
        function(result)
            if result[1] ~= nil then
                local playerName = ESX.GetPlayerFromIdentifier(result[1].owner).name
                cb(playerName, true)
            else
                cb('unknown', false)
            end
        end
    )
end)`

Sorry for posting on a closed issue, just tried to updated then fix it on my own and couldn't.

**Comment by ElPumpo** [comment]
It's commented in the code for a reason. It's not implemented yet.
