### ISSUE TITLE
Can't get or put money 

### ISSUE THREAD

**Issue by Meetook** [ESX-Org/esx_policejob#117]
Hi , i have a problem with the policejob. The menu "boss" can't work properlly, so i'cant put or get money, for help see the screen 
![policejoberror](https://user-images.githubusercontent.com/40768825/42173497-7b6b6162-7e1f-11e8-9943-d7a9bdb98340.PNG)
Please help me, help us

**Comment by ElPumpo** [comment]
inproper installation. make sure the society is properly setup.
