### ISSUE TITLE
Checking players unpaid bills

### ISSUE THREAD

**Issue by Lannebro** [ESX-Org/esx_policejob#121]
Hello. I would love to see a update that includes a check bills.. Wouldnt that be sweet? Our server is currently having the problem that the players arent paying the bills. And there is no way to know who have paid and not without checking database. Roleplay function that police can search db to see unpaid stuff would be super! Thanks

**Comment by ElPumpo** [comment]
Sure thing, implementing the function to a F6 menu is easy... I'll take a look at it
