### ISSUE TITLE
Colleague blips are sometimes not being shown

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_policejob#125]

**Comment by frayCORE** [comment]
So I think I solved it. You placed

`playerInService = true` and `playerInService = false`

after `TriggerEvent('esx_policejob:updateBlip')`

This causes the inverse to be true when it went to update blips. When I placed it right before `TriggerEvent('esx_policejob:updateBlip')` it seemed to solve the issue from the limited testing I did. Now it properly sets your blip viewing state.

**Comment by ElPumpo** [comment]
Has nothing to do with the service update. The bug is known to happen before the update aswell.

**Comment by stephen9898** [comment]
Still a issue

**Comment by KingpinNetwork** [comment]
Still not working.

**Comment by wallierocks2001** [comment]
any fix to this issue yet as i see many servers with this working
