### ISSUE TITLE
Improve in service system

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/esx_policejob#138]
Could it be possible to make it so you have the take the uniform to enter in service ?
And if not in service you don't receive the police call, don't show other officer on the map etc

Because at the moment even if not in uniforn, they can use the menu and it count as a cop in service for drug etc

**Comment by TemptressTeelia** [comment]
If you look at maybe truckerjob and see how they code it. They have what you are looking for and reuse it maybe?

**Comment by ElPumpo** [comment]
Yes that is the real fix. Remove going in service when taking out vehicles, and instead remove & add people in service when using the cloakroom
