### ISSUE TITLE
Unpaid Bills

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_policejob#140]
Unpaid Bills are not working. Im using latest esx_bills plugin.

Error running call reference function for resource esx_billing: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:95: attempt to index a nil value (local 'xPlayer')

**Comment by ElPumpo** [comment]
You broke it, great. How did you manage to break it?

**Comment by nykroza** [comment]
I have it on my server and it is working perfectly fine with the lastest version of esx_billing

**Comment by HumanTree92** [comment]
Yeah same here. Its working fine for me. I can check if a player has any unpaid bills & they show up. Found 1 of my Police Officers who play Civ a lot with over 10 unpaid fines.
