### ISSUE TITLE
Locales

### ISSUE THREAD

**Issue by Ultrunz** [ESX-Org/esx_policejob#146]
I just reinstalled fresh to see if it was something I was doing. 

Config.EnableJobBlip              = true -- enable blips for colleagues, requires esx_society

Config.MaxInService               = -1
Config.Locale = 'en'

Config.PoliceStations = {

My config.locale = 'en' always changes back to en and is saying 'no translation' in game, not sure whether it is from the updated plugin or something i am doing

**Comment by ElPumpo** [comment]
works just fine for me. you're doing something very wrong
