### ISSUE TITLE
Cant get into amory, vehiclespawn or locker after 1 Disconnect!

### ISSUE THREAD

**Issue by gediii** [ESX-Org/esx_policejob#148]
So everytime my cops leave the server and rejoin they cant access the armory, locker or garage anymore.
Would be nice if someone could help me with that!

**Comment by ExT3nD** [comment]
try reinstall the esx_policejob.

**Comment by ElPumpo** [comment]
Works just fine for everyone else? Unless you're going to provide useful information I can't help.
