### ISSUE TITLE
Change Drugs system to work with cops in service

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/esx_policejob#149]
Update esx_drugs so it work with the new system of cops in services.
Because at the moment even if you're not in service, it count as a cops

**Comment by nykroza** [comment]
esx_drugs_sv.lia

function CountCops()

	local xPlayers = ESX.GetPlayers()

	CopsConnected = 0

	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		if xPlayer.job.name == 'police' then
			CopsConnected = CopsConnected + 1
		end
	end

	SetTimeout(5000, CountCops)

end

CountCops()

**Comment by ElPumpo** [comment]
Misleading title this bug is not new
