### ISSUE TITLE
Police Car tracker

### ISSUE THREAD

**Issue by Hansen173** [ESX-Org/esx_policejob#150]
Instead of making it so you can see your fellow officers then maybe do so you can switch between either wanting to see only cars or if you wanna see only officers, in the terms of RP. so when you find the car you might need to search for the officer.

**Comment by LuaDeldu** [comment]
Very good idea. And maybe not a real-time tracker. Something like a tracker update every 30-60s in order to balance legal and illegal ways.

**Comment by Hansen173** [comment]
Exactly something to spice the roleplay a Little

**Comment by ElPumpo** [comment]
Not gonna happen, if you want it then implement it yourself
