### ISSUE TITLE
Custom ped won't spawn

### ISSUE THREAD

**Issue by PERPGamer** [ESX-Org/esx_policejob#159]
Whenever anyone try to select Sheriff Wear, Police Wear, or SWAT Wear, it doesn't do anything. Don't show any errors or change the player's ped. When I commented out `ESX.Streaming.RequestModel(modelHash, function()` one of the models worked but the rest crashed the game.

**Comment by ElPumpo** [comment]
Update esx then. Loading assets that haven't been loaded will always crash clients.
