### ISSUE TITLE
error in OpenGetStocksMenu()

### ISSUE THREAD

**Issue by manups4e** [ESX-Org/esx_policejob#178]
in function OpenGetStocksMenu()

in line 1166: table.insert(elements, {label = 'x' .. items[i].count .. ' ' .. items[i].label, value = items[i].name})

i get a nil value on items[i].count 
using latest esx_policejob and latest esx_addoninventory

**Comment by nykroza** [comment]
that can happen if you changed a item name and that the last one is still inside the vault

**Comment by manups4e** [comment]
i double checked and no items name has been changed

**Comment by manups4e** [comment]
i get some phantom items in the menu when i remove count.. the problem is that in database i don't have those items... 
![screenshot 391](https://user-images.githubusercontent.com/4005518/44603249-67292f80-a7e2-11e8-9295-30d4393474bc.png)
![immagine](https://user-images.githubusercontent.com/4005518/44603298-832cd100-a7e2-11e8-95a5-a47e3fbcbc9b.png)

**Comment by manups4e** [comment]
maybe i found the error... somebody placed some weapons so i deleted them but not yet restarted my server.. anyway.. maybe the 2 weapons (not actually items in database) were the problem

**Comment by manups4e** [comment]
Solved (weapons stored in stock)
