### ISSUE TITLE
When SocietyOwnedVehicle true, is possible make whitelisted cars for certain ranks?

### ISSUE THREAD

**Issue by MoravianLion** [ESX-Org/esx_policejob#184]
Hi,

when I've changed vehicles to OwnedSociety as true, they were available to all ranks (instead of previous custom config preset). Owned by society option allowes to actually lock the police cars thx to locking script.

Would be possible to add option for vehicles owned by society, so those cars are visible ONLY to certain ranks? That would be amazing!

**Comment by rpgsa** [comment]
You can just amend the file config.lua (and you will also need to update the clients/main.lua file too) to show what police cars are available depending on rank, so for me, if you work in LSPD you only get LSPD vehicles, but you can only drive things like unmarked if you are Sgt or above. 
You can also change the code in this file to reflect what uniform they need to wear as well depending on rank and department.
I have attached a snippet of what I did to change all mine
Ensure you backup any files first, but this should get you started for what you want.
[policejob.txt](https://github.com/ESX-Org/esx_policejob/files/2373933/policejob.txt)

**Comment by MoravianLion** [comment]
Thank you! I was thinking about doing the same lately. :+1:

**Comment by ElPumpo** [comment]
This is nothing we're going to offically support. I see the vehicle society system as deprecated, and it might be removed in the future when the entire Vehicle system gets revamped again. Officers will have to purchase their own police cars.
