### ISSUE TITLE
object_spawner

### ISSUE THREAD

**Issue by PrayGayben-Qc** [ESX-Org/esx_policejob#193]
Spikestrips don't wanna come off with [E].

**Comment by ElPumpo** [comment]
Works just fine for me?

**Comment by daffiestfrog41** [comment]
Im having a problem with object spawner as well. I have 3 different police deparments in my server so essentially esx_policejob, esx_saspjob, and esx_bcso job. The last two are pretty much just copies of policejob with some obvious changes. The only issue is the object spawner works only on esx_policejob but not on the other two. Any thoughts?
