### ISSUE TITLE
Cannot check plate with player inside vehicle

### ISSUE THREAD

**Issue by ghost** [ESX-Org/esx_policejob#20]
There is a bug, when you attempt to check vehicle info when another player is in the vehicle, it says "no vehicles nearby"

**Comment by RomainLanz** [comment]
Hey @XBVY! 👋 

Thanks for your report!
I can replicate this and I'll try to fix it asap.

**Comment by bendenny** [comment]
Hey there! Wanted to say I’m still seeing this issue

**Comment by HumanTree92** [comment]
2 Months later and it is still happening.

**Comment by ElPumpo** [comment]
Fixed, make sure you update ESX
