### ISSUE TITLE
Cuff / Uncuff / Escort and put in vehicle

### ISSUE THREAD

**Issue by Valkatastz** [ESX-Org/esx_policejob#203]
These options are not working. I checked there similar but not the one related to my issue exactly. I am using es_extended 1.0.14 and 1.3.0 for policejob and latest updates for it's dependencies. However, these options for the police aren't working. I can't handcuff anyone, nor escort him nor put him in vehicle same for the medics (put in vehicle). Who can sort this out?

**Comment by apostoloskotsiras** [comment]
me too i cant uncuff idk why

**Comment by Gbronski** [comment]
Any news?

**Comment by Kruxgaming** [comment]
I have fixed the esx_policejob by modifying the code
