### ISSUE TITLE
F6 menu

### ISSUE THREAD

**Issue by Bazookan** [ESX-Org/esx_policejob#207]
Check identity and search dosen’t work in the f6 menu. Might be something wrong in es_extended, not sure yet since i haven’t looked in to it that much.

**Comment by precoder97** [comment]
The player you are checking needs to have a license

**Comment by Bazookan** [comment]
Oh yeah...thats right! But you should still be able to search, wich you aren’t.

**Comment by lenzh** [comment]
Still not fixed..

**Comment by LuffyCosta** [comment]
Just do, as i did on my configs for now, create a license that everybody has. In the licenses table create a civil type, then in the ESX identity on the setIdentity function add a mysql async task to insert into the user licenses with the steam id and the civil licence. This way every user has a license  ;) hope i could help

**Comment by ElPumpo** [comment]
Duplicate
