### ISSUE TITLE
helicopter spawner doesn't appear

### ISSUE THREAD

**Issue by radiodrag** [ESX-Org/esx_policejob#209]
I teleported directly on the spot but there's no spawner there (latest and previous versions)

**Comment by Ultrunz** [comment]
There is no spawner. It auto spawns on the helipad as you walk through the 'spawner'.

**Comment by ElPumpo** [comment]
Theres no spawner available like cars. If youre at the spawner coords it will spawn a heli

**Comment by ElPumpo** [comment]
See #108
