### ISSUE TITLE
Player still handcuffed after respawn

### ISSUE THREAD

**Issue by ElRocaYT** [ESX-Org/esx_policejob#21]
If a player die hancuffed they respawn still handcuffed on the hospital.

**Comment by Arimanio** [comment]
If you've spent anytime RP'ing as a cop this is actually a desirable effect. I hope this doesn't change or if it does, the option remains to keep them handcuffed on death.

**Comment by ElPumpo** [comment]
Way too easy to fix, `isHandcuffed` is a boolean, just set it to `false` when setting `isDead`
