### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by ProxyAcid** [ESX-Org/esx_policejob#214]
Error running call reference function for resource esx_society: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:219: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:219: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM users WHERE job = @job ORDER BY job_grade DESC {@job=police}"

**Comment by ElPumpo** [comment]
Not this resource
