### ISSUE TITLE
Startup problem.

### ISSUE THREAD

**Issue by FreddieDK** [ESX-Org/esx_policejob#218]
I have this problem with the policejob where i do /setjob 1 police 3, and it works fine. I can then use F6 to get the police menu and interact with the job actions, however when i disconnect and reconnect… it says i’m LSPD but i can’t use the F6 menu either interact with the job actions.

Please Help.

**Comment by FreddieDK** [comment]
Is there a way I can make it reload on startup?

**Comment by lenzh** [comment]
replace
```
Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        Citizen.Wait(0)
    end
    
    PlayerData = ESX.GetPlayerData()
end)
```


with 
```
Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        Citizen.Wait(0)
    end

    while ESX.GetPlayerData().job == nil do
        Citizen.Wait(10)
    end

    PlayerData = ESX.GetPlayerData()
end)
```
in client
