### ISSUE TITLE
vehicle price can't be 0

### ISSUE THREAD

**Issue by Chip-W** [ESX-Org/esx_policejob#219]
If I set police vehicles to 0 for the price, I get a notification saying I don't have enough money.  I set it to 1000, I can then purchase.  I haven't tried any other numbers.

**Comment by luggz** [comment]
Can this not be disabled? and it be like the old way? hard to make this work in whitelisted job foe economy servers....

**Comment by ElPumpo** [comment]
Then dont update luggz?! Chip vehicles aren't supposed to be free, and yes don't set vehicle prices to 0 as that's what the server sided function returns when the vehicle parsed isn't found.
