### ISSUE TITLE
Spawning bought vehicles

### ISSUE THREAD

**Issue by LoffeKoffe** [ESX-Org/esx_policejob#223]
error running call reference function for recource esx_policejob: citizen:/scripting/lua/scheduler.lua:403 client/main.lua:534: attempt to index a nil value (field '?')
stack traceback:
clinet/main.lua:534: in function 'GetAvailableVehicleSpawnPoint'

**Comment by LoffeKoffe** [comment]
Helikoptrarna fungerar dock perfekt
de är bara spawna bilarna som krånglar

**Comment by Iceman997799** [comment]
I get this error too. Everything else seems to work but the cars.

**Comment by Iceman997799** [comment]
ok found the issue and check to make sure it worked
in the folder esx_policejob\client\main.lua line #396 change
from
local foundSpawn, spawnPoint = GetAvailableVehicleSpawnPoint(, 'Vehicles', partNum)  
to 
local foundSpawn, spawnPoint = GetAvailableVehicleSpawnPoint(station, 'Vehicles', partNum)
this fixes the issues with the car garage not spawning

**Comment by LoffeKoffe** [comment]
hmm, well it worked, heh, thanks!

**Comment by LoffeKoffe** [comment]
Nope now the helikopters spawn at the car spawnpoints...

**Comment by DayZen16** [comment]
ok so here's the fix...

Change line 1538 to elseif part == 'Vehicles' then instead of  elseif part == 'VehicleSpawner' then

and line 1880 to 
isInMarker, currentStation, currentPart, currentPartNum = true, k, 'Vehicles', i
