### ISSUE TITLE
Cant open marker menus

### ISSUE THREAD

**Issue by LoffeKoffe** [ESX-Org/esx_policejob#225]
everytime i start my server or restart the script i need to restart the script altleast once (often more ) to be able to open the menus, anyone with the same problem?

**Comment by Iceman997799** [comment]
I got no issues with the policejobs after the fix I posted. watch the client debug to see what errors you get.

**Comment by LoffeKoffe** [comment]
problemet ligger här:
`if not hasExited and not isInMarker and HasAlreadyEnteredMarker then
	HasAlreadyEnteredMarker = false
	TriggerEvent('esx_policejob:hasExitedMarker', LastStation, LastPart, LastPartNum)
end`

tar jag bort:
TriggerEvent('esx_policejob:hasExitedMarker', LastStation, LastPart, LastPartNum)

så inte menyerna stängs så fungerar de perfekt förutom att menyerna inte stängs när du går där ifrån.
har gjort en tillfällig lösning på min server som fungerar.

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/esx_policejob/commit/adea5f713b1888f89e666d42847441de77996eb9
