### ISSUE TITLE
Fail update 1.0.1 to last version

### ISSUE THREAD

**Issue by LilEligius** [ESX-Org/esx_policejob#226]
When I update to the latest version nothing works on esx_policejob, I have 1.0.1 if I'm not wrong and that works fine, but when I update I see the points but I can not access the menu. How can I solve that?

**Comment by LoffeKoffe** [comment]
same problem here, i get the "press e to ..." but cant open it. i have a temporary fix on my server until this hopefully works. otherwise ill have to go back to the old version again

**Comment by ElPumpo** [comment]
You will have to much more spefic on the problem
