### ISSUE TITLE
Issue with the new Weapons MK2?

### ISSUE THREAD

**Issue by Jonneis** [ESX-Org/esx_policejob#228]
Im trying to add the MK2  weapons but it doesnt work, for example when i add the PISTOL MK2 the menu doesnt show up.

 { weapon = 'WEAPON_PISTOL_MK2', components = { 0, 0, 1000, 4000, nil }, price = 10000 },
 { weapon = 'WEAPON_NIGHTSTICK', price = 0 },
 { weapon = 'WEAPON_STUNGUN', price = 1500 },
 { weapon = 'WEAPON_FLASHLIGHT', price = 80 }

and for some reason the components doesnt work,idk if i have to update something else....

**Comment by ElPumpo** [comment]
Mk2 not supported
