### ISSUE TITLE
Error with the new es_extended

### ISSUE THREAD

**Issue by spotniik** [ESX-Org/esx_policejob#235]
I cannot get weapons from the armory menu... I'm using the new es_extended update
![1](https://user-images.githubusercontent.com/46611332/51060305-a6b8b280-15ef-11e9-9da4-d182698537e1.PNG)
![2](https://user-images.githubusercontent.com/46611332/51060312-aa4c3980-15ef-11e9-8927-cca24cd51249.PNG)

**Comment by Schwardo19462** [comment]
I've got the same Problem. Can't get Weapons or buy Vehicles

**Comment by MrMallenby** [comment]
same problem here

**Comment by ElPumpo** [comment]
Idiot that means that you are running an OLD version of esx.
