### ISSUE TITLE
unable to buy vehicles

### ISSUE THREAD

**Issue by mifsopo** [ESX-Org/esx_policejob#237]
when i go to the vehicleshop it shows me the police cars but refuses to allow me to buy them
![error](https://user-images.githubusercontent.com/44308680/51124166-a258e900-17eb-11e9-83e3-ca62392f9639.PNG)
i have no idea why its doing this, theres no error in my actual console
![entity](https://user-images.githubusercontent.com/44308680/51124204-b997d680-17eb-11e9-9fdc-9e3f2131269c.PNG)
and i get this after i back out of the garage, if i can get any help i would much appriciate it <3

**Comment by ElPumpo** [comment]
Make sure every esx resource is up to date
