### ISSUE TITLE
No spawning vehicles

### ISSUE THREAD

**Issue by SydeSB-EST** [ESX-Org/esx_policejob#241]
How i fix this error? Gosh. I have headache bc of this. ES Extended are updated, EssentialMode is updated... What im doing wrong? I have latest esx policejob. 
When i go to "get vehicle" point, then i have 3 options there. How this supposed to work? I just want to let police get his vehicles. Gosh. When i click Store Vehicle then i get 3 errors. Others just saying i don't have any vehicles in garage or i don't have any nearby owned vehicles... Idk what to do. Im so pissed.
**Those are these 3 errors:** 
![storevehicle](https://user-images.githubusercontent.com/46901813/51490964-96ee5a80-1db5-11e9-9ea2-ad8e52817474.PNG)
![storevehicle2](https://user-images.githubusercontent.com/46901813/51490972-9a81e180-1db5-11e9-9a77-6ba2ae946a5f.PNG)
![storevehicle3](https://user-images.githubusercontent.com/46901813/51490977-9e156880-1db5-11e9-9848-131aa8e12d05.PNG)

**Comment by Albin323** [comment]
In the new version you need to buy cop cars, have you done that?

**Comment by ElPumpo** [comment]
Works just fine if all dependencies are properly up to date
