### ISSUE TITLE
Problème Open Garage

### ISSUE THREAD

**Issue by GeKOfficiel** [ESX-Org/esx_policejob#242]
Bonjour, je vous écrit ce message car y'a un soucis avec les véhicule import quand nous allons dans le open garage le véhicule s'appel NULL.
Pouvais vous m'aidez.
Merci

**Comment by dolutattoo** [comment]
Ton vehicule addon possède-t-il bien un fichier vehicle_name.lua ?

**Comment by ElPumpo** [comment]
Um English? Resoruce works just ok if all dependencies are up to date.
