### ISSUE TITLE
Getting stuck in garage

### ISSUE THREAD

**Issue by vernietiger** [ESX-Org/esx_policejob#243]
Hey, 

So i updatet everything and even did a reinstal of everything. But now i open the menu and then i spawn in the garage. As soon as i spawn in the garage the menu disapears. so i cant leave garage. I use admin powers. And if i get into a new vehicle that i get stuck in the vehicle

Hope u can help! 

I use eden garage

**Comment by vernietiger** [comment]
Nice...

**Comment by Aaronh0103** [comment]
Any fix for this? I am also having the same issue. I can't have everyone have admin powers so they can TP themselves out.
