### ISSUE TITLE
Esx_policejob skin bug and vehicles intracaction bug

### ISSUE THREAD

**Issue by Tom-NL** [ESX-Org/esx_policejob#244]
I have a bug with me esx police job,
that if I want to pack my own skin then who does not know you know the solution?

**Comment by Tom-NL** [comment]
and also have a bridge with the vehicles intracaction

**Comment by Albin323** [comment]
pack my own skin? How do you exactly mean?

**Comment by Tom-NL** [comment]
own Dutch skins etc. @Albin323

**Comment by ElPumpo** [comment]
Not a issue with this resource
