### ISSUE TITLE
Problem with garage

### ISSUE THREAD

**Issue by vernietiger** [ESX-Org/esx_policejob#247]
When i open the garage i get a small menu for seconds, when i spawn into the garage the menu just goes away and i get stuck. I get this error:

[   2423141] NETWORK_GET_NETWORK_ID_FROM_ENTITY: no net object for entity
[   2423141] NETWORK_GET_NETWORK_ID_FROM_ENTITY: no net object for entity
[   2423141] NETWORK_GET_NETWORK_ID_FROM_ENTITY: no net object for entity
[   2423141] GetNetworkObject: no object by ID 13570

I use the latest version of all the needed recources and i use eden garage.

**Comment by VojtaCZE** [comment]
get an old one. I have it, but its broken.. Do you want me to send it to you?

**Comment by ElPumpo** [comment]
It works just fine if properly setup

**Comment by FBFezz** [comment]
Im getting the same thing but i have set mine up properly
