### ISSUE TITLE
Can't buy weapons from armoury

### ISSUE THREAD

**Issue by MeerkatRS** [ESX-Org/esx_policejob#254]
Used to work I believe but I now can't buy weapons from the armoury all of a sudden. It takes money but doesn't give me it. Everything else seems to work. 
![image](https://user-images.githubusercontent.com/31329492/53288549-55204d80-3781-11e9-8f6d-cb82d48b8046.png)

**Comment by Janicki92** [comment]
Same issue here

**Comment by ThatGuyJacobee** [comment]
Yeah same issue in my server.

**Comment by WaveShredder** [comment]
For those of you still having this issue, I received great help in fixing this from the community on the ESX Discord by (Sojobo).

To fix this, you need to add this code to: es_extended\shared\functions.lua 

```
ESX.GetWeapon = function(weaponName)
    weaponName = string.upper(weaponName)
    local weapons = ESX.GetWeaponList()

    for i=1, #weapons, 1 do
        if weapons[i].name == weaponName then
            return i, weapons[i]
        end
    end
end
```

**Comment by Guy293** [comment]
> For those of you still having this issue, I received great help in fixing this from the community on the ESX Discord by (Sojobo).
> 
> To fix this, you need to add this code to: es_extended\shared\functions.lua
> 
> ```
> ESX.GetWeapon = function(weaponName)
>     weaponName = string.upper(weaponName)
>     local weapons = ESX.GetWeaponList()
> 
>     for i=1, #weapons, 1 do
>         if weapons[i].name == weaponName then
>             return i, weapons[i]
>         end
>     end
> end
> ```

Thank you. You should pull request this to esx.

**Comment by iSlo7e21** [comment]
> es_extended\shared\functions.lua

i don't have this folder es_extended\shared in es_extended !

**Comment by WaveShredder** [comment]
I know, they’ve changed it. From my understanding, this has already been added to the originial es extended release. You shouldn’t have to do this anymore 😀

**Comment by iSlo7e21** [comment]
> I know, they’ve changed it. From my understanding, this has already been added to the originial es extended release. You shouldn’t have to do this anymore 😀

I have same problem when i add custom item in config.lua it dosen't work

`	recruit = {
		{ weapon = 'WEAPON_APPISTOL', components = { 0, 0, 1000, 4000, nil }, price = 10000 },
		{ weapon = 'WEAPON_NIGHTSTICK', price = 0 },
		{ weapon = 'radio', price = 0 },
		{ weapon = 'WEAPON_STUNGUN', price = 1500 },
		{ weapon = 'WEAPON_FLASHLIGHT', price = 80 }
	},`
![Screenshot_110](https://user-images.githubusercontent.com/49908129/56812367-68b06900-6843-11e9-9ea4-bde3c64fdffd.png)
![Screenshot_111](https://user-images.githubusercontent.com/49908129/56812377-6cdc8680-6843-11e9-8e79-4818eacbadd3.png)

**Comment by Guy293** [comment]
@iSlo7w21
Do you have that item in the database?
And are you referring to the radio?

**Comment by iSlo7e21** [comment]
> @iSlo7w21
> Do you have that item in the database?
yes I have it in [items]
![Screenshot_113](https://user-images.githubusercontent.com/49908129/56828535-2bab9d00-686a-11e9-88ba-b28a9b03cf0e.png)
> And are you referring to the radio?
how I can do this ?

**Comment by Guy293** [comment]
You can only add weapons. Not items.

**Comment by iSlo7e21** [comment]
> You can only add weapons. Not items.

I need to add item how i can do it ?
if you have another script I can add items to ambulance and police help me.
