### ISSUE TITLE
May i release a modified fork?

### ISSUE THREAD

**Issue by wolfpepper** [ESX-Org/esx_policejob#255]
i am wanting to request if i can release my modified version of this script where i have made a park ranger job out of it I have several people on my server who wanted to be park rangers as we do have alot of jobs that would require enforcement of Fishing/Hunting laws i also think that something like this would be a benefit to the community surrounding fivem as ive spoken to several servers that have fishing/ hunting jobs and are wanting a legit way to enforce the laws surrounding anything dealing with game/wildlife

**Comment by ElPumpo** [comment]
Fork here 
![image](https://user-images.githubusercontent.com/12564301/53688936-be88f900-3d4b-11e9-8a33-89ac933f205e.png)

share the link however you want
