### ISSUE TITLE
TriggerSererCallback => [esx_service:isInService] does not esxist

### ISSUE THREAD

**Issue by eugenecarr** [ESX-Org/esx_policejob#256]
I recently installed this onto my server as well as the required dependencies listed on the github however I am unable to go on duty due to an error preventing me from "going in service" the error I recieve from my console is **TriggerSererCallback => [esx_service:isInService] does not esxist**

Most of the config is stock (Locale and a few minor things changed) but no other files related were edited.
https://pastebin.com/DxiK6A59 Here is my config if it helps

I looked online for esx_society and found a resource however using it just generates alot more errors (Screenshots)
Without esx_service : https://gyazo.com/2f42420a78127ca67d85f1fb2701e4c3
With esx_service : https://gyazo.com/0a52af75c124af8dac9e87da3ea8da31

Any help would be greatly appreciated :)

**Comment by ElPumpo** [comment]
Update esx_service

**Comment by eugenecarr** [comment]
My esx_service is up to date according to the github repo but still the error occurs

**Comment by eugenecarr** [comment]
also it doesnt mention in the requirements that esx_service should be installed
