### ISSUE TITLE
Can't deposit/withdraw weapons from Armory

### ISSUE THREAD

**Issue by ArkSeyonet** [ESX-Org/esx_policejob#259]
function OpenPutStocksMenu() (Client/main.lua - Line 1444) it errors after Line 1462
function OpenGetStocksMenu() (Client/main.lua - Line 1393) it errors after Line 1406

nui://esx_menu_default/html/js/app.js:69, Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined

The result for both trying to deposit or withdraw weapons results in the UI popping up but the list of items never populating or showing.

**Comment by Janicki92** [comment]
I also cannot withdraw.  Depositing seems to work, as it takes the weapon and shows the UI.
Withdrawing does not work whatsoever.

**Comment by ElPumpo** [comment]
Make sure datastore is properly setup

**Comment by Janicki92** [comment]
It is.  this does not fix the issue.
