### ISSUE TITLE
CANT SEE PD BLIPS

### ISSUE THREAD

**Issue by stephen9898** [ESX-Org/esx_policejob#260]
hi i enable blips for colleges but when in server it dost show them on the map can you please help me fix this updated all resources

**Comment by RedAlex** [comment]
Same for us
We have update all to today and same problem with all original ressource.
Blips will show 0.1 second 
I continu to investigate.

**Comment by stephen9898** [comment]
they wont show at all for us

**Comment by RedAlex** [comment]
Test done :
Rollback server version to 1034 : Blips Not Work
Rollback essentialsmode to 5.0.2 : Blips Not Work
Rollback esx_policejob to 2 years ago : Blips Not Work
Erase fivem client cache : Blips Not Work
I continu to investigate.

**Comment by RedAlex** [comment]
Found code in another ressource to remove player blips on map.
Fix for us.

**Comment by stephen9898** [comment]
can you share please

**Comment by ElPumpo** [comment]
Dupe of #125
