### ISSUE TITLE
Vehicle not in Garage after client crash

### ISSUE THREAD

**Issue by TakuyaSan420** [ESX-Org/esx_policejob#261]
Hello,
I have a little Problem. If someones game crashes and he is driving a police car (bought from the job garage), and he comes back the car is not at the same place as he left anymore (obviously it despawned) but where can he retrieve it again? Because it says thats its not in the garage so he cant get it that way, It isnt in the impound lot either
Thanks for help

**Comment by mifsopo** [comment]
same issue

**Comment by ElPumpo** [comment]
The problem here is vehicle despawning.. See esx issue for this
