### ISSUE TITLE
es_extended ignoring jobs

### ISSUE THREAD

**Issue by KristjanMesitaru** [ESX-Org/esx_policejob#262]
es_extended: invalid job “police” from table job_grades ignored!
es_extended: invalid job “police” from table job_grades ignored!
es_extended: invalid job “police” from table job_grades ignored!
es_extended: invalid job “police” from table job_grades ignored!
es_extended: invalid job “police” from table job_grades ignored!
es_extended: invalid job “ambulance” from table job_grades ignored!
es_extended: invalid job “ambulance” from table job_grades ignored!
es_extended: invalid job “ambulance” from table job_grades ignored!
es_extended: invalid job “ambulance” from table job_grades ignored!
es_extended: invalid job “cardealer” from table job_grades ignored!
es_extended: invalid job “cardealer” from table job_grades ignored!
es_extended: invalid job “cardealer” from table job_grades ignored!
es_extended: invalid job “cardealer” from table job_grades ignored!
es_extended: invalid job “lumberjack” from table job_grades ignored!
es_extended: invalid job “reporter” from table job_grades ignored!
es_extended: invalid job “slaughterer” from table job_grades ignored!
es_extended: invalid job “offpolice” from table job_grades ignored!
es_extended: invalid job “offpolice” from table job_grades ignored!
es_extended: invalid job “offpolice” from table job_grades ignored!
es_extended: invalid job “offpolice” from table job_grades ignored!
es_extended: invalid job “offpolice” from table job_grades ignored!
es_extended: invalid job “offambulance” from table job_grades ignored!
es_extended: invalid job “offambulance” from table job_grades ignored!
es_extended: invalid job “offambulance” from table job_grades ignored!
es_extended: invalid job “offambulance” from table job_grades ignored!
es_extended: invalid job “avocat” from table job_grades ignored!
es_extended: invalid job “mechanic” from table job_grades ignored!
es_extended: invalid job “mechanic” from table job_grades ignored!
es_extended: invalid job “mechanic” from table job_grades ignored!
es_extended: invalid job “mechanic” from table job_grades ignored!
es_extended: invalid job “mechanic” from table job_grades ignored!
es_extended: invalid job “realestateagent” from table job_grades ignored!
es_extended: invalid job “realestateagent” from table job_grades ignored!
es_extended: invalid job “realestateagent” from table job_grades ignored!
es_extended: invalid job “realestateagent” from table job_grades ignored!
es_extended: invalid job “gopostal” from table job_grades ignored!

**Comment by KristjanMesitaru** [comment]
what i need to do

**Comment by ElPumpo** [comment]
Add your jobs to `jobs` too
