### ISSUE TITLE
Can't buy weapons. erroring at ESX.GetWeapon(v.weapon)

### ISSUE THREAD

**Issue by mrdigital0** [ESX-Org/esx_policejob#263]
When trying to buy weapons the line:  

local weaponNum, weapon = ESX.GetWeapon(v.weapon)

 in the OpenBuyWeaponMenu is erroring out..  

ESX Documenation doesn't show that as a valid function.

**Comment by McDo-TBT** [comment]
I've same problem. It's strange ..

**Comment by mrdigital0** [comment]
i fixed this issue by removing es_extended and reinstalling it

**Comment by Nevos08** [comment]
Did the same, but it didnt work
