### ISSUE TITLE
Buy weapons

### ISSUE THREAD

**Issue by McDo-TBT** [ESX-Org/esx_policejob#264]
![Screenshot_1](https://user-images.githubusercontent.com/48632844/54487212-9f35b400-4893-11e9-84f0-df0fefe5c00e.png)

local weaponNum, weapon = ESX.GetWeapon(v.weapon)

When trying to buy weapons in armory.
I updated es_extended and all esx ui

**Comment by CanGamers** [comment]
same issue, this is a big one as you there's no load outs given to the police when going on duty and you cant restock the armory.
