### ISSUE TITLE
Issue with garage car names

### ISSUE THREAD

**Issue by VojtaCZE** [ESX-Org/esx_policejob#269]
Will there be any way in the future to change the car labels in garage not in shop?

I'll be very thankful if there will be that function. Or is there any way? Respond, thank you.

**Comment by Janicki92** [comment]
Agreed.  I have tried even adding a vehicle_name.lua file to my add-ons and it did nothing..

**Comment by ElPumpo** [comment]
The vehicle label is being fetched from metadata yes. You must define all vehicle labels, especally addon vehicles
