### ISSUE TITLE
Can only put 1 person in vehicle

### ISSUE THREAD

**Issue by MeerkatRS** [ESX-Org/esx_policejob#270]
You can only put one person into a vehicle. We have to make multiple stops to PD to pick everyone up.

**Comment by MeerkatRS** [comment]
Still having this issue. Nobody seems to want to help with this. I'd have thought this would be almost a necessity.

**Comment by daniel96rk** [comment]
> Still having this issue. Nobody seems to want to help with this. I'd have thought this would be almost a necessity. Using latest version.

Problem lies with the drag code. What you can do and should do is modify the handcuff code to better allow movement such as running while handcuffed and entering vehicles. This way you can force multiple handcuffed people into the same car through roleplay.

**Comment by MeerkatRS** [comment]
> > Still having this issue. Nobody seems to want to help with this. I'd have thought this would be almost a necessity. Using latest version.
> 
> Problem lies with the drag code. What you can do and should do is modify the handcuff code to better allow movement such as running while handcuffed and entering vehicles. This way you can force multiple handcuffed people into the same car through roleplay.

I commented out all the drag code and all the handcuff disable controls. They can run around while handcuffed but still same issue. Doesn't fix putting into vehicle.

**Comment by daniel96rk** [comment]
> > > Still having this issue. Nobody seems to want to help with this. I'd have thought this would be almost a necessity. Using latest version.
> > 
> > 
> > Problem lies with the drag code. What you can do and should do is modify the handcuff code to better allow movement such as running while handcuffed and entering vehicles. This way you can force multiple handcuffed people into the same car through roleplay.
> 
> I commented out all the drag code and all the handcuff disable controls. They can run around while handcuffed but still same issue. Doesn't fix putting into vehicle.

That's because you dont understand the solution. If you allow people to use controls while they are cuffed you can "ROLEPLAY" them into the car.

**Comment by ElPumpo** [comment]
Dupe
