### ISSUE TITLE
Purchased Police Vehicles Not Stored

### ISSUE THREAD

**Issue by Janicki92** [ESX-Org/esx_policejob#271]
Even after restarting the server, clearing cache, I have police vehicles in my garage that say "NOT IN GARAGE" and are not able to be retrieved....

There is no impound that I'm aware of so why are these vehicles not resetting at server restart?

**Comment by daniel96rk** [comment]
> Even after restarting the server, clearing cache, I have police vehicles in my garage that say "NOT IN GARAGE" and are not able to be retrieved....
> 
> There is no impound that I'm aware of so why are these vehicles not resetting at server restart?

Redo the garage code yourself to solve this problem. What you can do in the meantime is to change the database value of said police car to "stored = 0" to "stored = 1".
