### ISSUE TITLE
Old garage but new armory?

### ISSUE THREAD

**Issue by Mariox6** [ESX-Org/esx_policejob#272]
Hello,

is there a way to have the old garage (only choose vehicle to spawn) with the new armory?

**Comment by lvp11** [comment]
I want it too, someone known a way?

**Comment by daniel96rk** [comment]
> Hello,
> 
> is there a way to have the old garage (only choose vehicle to spawn) with the new armory?

Just use the old garage code then?

**Comment by Mariox6** [comment]
How? I tried it more than 5 times but it didn´t worked ;(

**Comment by Cactusje** [comment]
I am currently working on this on my Fork project, to get some old features back a lot of people love and care about :)

**Comment by Mariox6** [comment]
Can you tell me when you are finished? @Cactusje

**Comment by Mariox6** [comment]
When do you think you are done?
