### ISSUE TITLE
Got this issue when trying to spawn any of the uniforms 

### ISSUE THREAD

**Issue by orros01** [ESX-Org/esx_policejob#275]
The first pic when I press any of the 4 button nothing happens no changes on the character and i am police on the server 
![image](https://user-images.githubusercontent.com/49104846/55728329-2b12aa00-5a14-11e9-9f99-32ea1e868530.png) 
when I press any of the 4 buttons this pops up in the console
![image](https://user-images.githubusercontent.com/49104846/55728535-86449c80-5a14-11e9-9dd8-1d16c7a73b45.png)

**Comment by daniel96rk** [comment]
There error is right there in the console, why do you even attempt to create a server when you can't even read?
