### ISSUE TITLE
Can't open f6 menu

### ISSUE THREAD

**Issue by wydox1SK** [ESX-Org/esx_policejob#280]
Hello,

for some reason i cannot open my f6 menu on policejobs or ambulancejobs, i am getting no error in my console or in game.. I have completely rebuilt my database and made sure every resource i am running is up-to-date but still no success. My normal inventory menu is fine as well as some others but for some reason these two jobs don't want to work for some reason. I would appreciate any help i can get, thanks.

**Comment by Mariox6** [comment]
Same probleme

**Comment by jeffgraeber** [comment]
I am also having the same issues along with the PD location blips not showing. everything is up to date, anyone have suggestions or a fix?

**Comment by jeidenzi** [comment]
same problem
