### ISSUE TITLE
Store And Release Society Cars

### ISSUE THREAD

**Issue by DonKKijotE** [ESX-Org/esx_policejob#284]
Hello guys, I have noticed that there is an issue with police cars and storing them in the police garage depending if they are society cars or private cars.

If the car is a police car and belongs to a police officer then it can be entered in the garage and then taken out. The problem happens when you buy a car for the police society, in that case you can't store it ir take it out of the garage.

Regarding getting the society car out of the garage:

I noticed that the policejob garage  uses "esx_vehicleshop:retrieveJobVehicles" to get the list of work cars in the garage, and that function/method works like this:

ESX.RegisterServerCallback('esx_vehicleshop:retrieveJobVehicles', function (source, cb, type)
	local xPlayer = ESX.GetPlayerFromId(source)

	MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND type = @type AND job = @job', {
		['@owner'] = xPlayer.identifier,
		['@type'] = type,
		['@job'] = xPlayer.job.name
	}, function (result)
		cb(result)
	end)
end)

This means that when you go to the police garage you are seeing the police vehicles that belong to that owner. If you wanted to see the society vehicles you would have to change 

['@owner'] = xPlayer.identifier, 

    into 

['@owner'] = 'society:' .. xPlayer.job.name, .

The problem would be, and I can't find a fix, that when you try to store a vehicle in the police garage the function StoreNearbyVehicle(playerCoords) won't let you store society vehicles, only your private police cars which will later not be listed in the garage.

Could anyone give me some information on how to be able to store society vehicles? Thanks on beforehand and good job!

**Comment by DonKKijotE** [comment]
Hey guys, I managed to fix it. I'm gonna make a small explanation on how to be able to purchase cars for the police society and be able to store them  in the police garage and take them out as well.

When you want to see what police cars are in the garage the esx_policejob resource calls the function esx_vehicleshop:retrieveJobVehicles, which contains the following code:

```
ESX.RegisterServerCallback('esx_vehicleshop:retrieveJobVehicles', function (source, cb, type)
local xPlayer = ESX.GetPlayerFromId(source)

MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND type = @type AND job = @job', {
	['@owner'] = xPlayer.identifier,
	['@type'] = type,
	['@job'] = xPlayer.job.name
}, function (result)
	cb(result)
end)
end)
```

As you can see, mySQL is retrieving all the vehicles which belong to that user and are for that specific job. As you can see, this disables the possibility of purchasing society cars and being able to handle them.

In my server, I want police cars to belong to the police society and having them stored in the police garage. Likewise, in all other jobs in my server I think I will do it like that. So what I do is, from the previous code change:

`['@owner'] = xPlayer.identifier,`

into

`['@owner'] = 'society:' .. xPlayer.job.name, `

With this modification what you're telling esx_vehicleshop to do when asked to retrieveJobVehicles is to look for vehicles owned by a specific society and not by a specific user. In my opinion this makes sense since, when you go to the vehicle shop and purchase a vehicle for a society it sets the owner to society:XXXXX instead of steam:XXXXX. Now when we go to the police garage and open it we will see the vehicles that belong to the police society and get them out.

Now the problem left is being able to put the society cars in the garage. The fix to this is going to esx_policejob/server/main.lua and look for the following function to do the same as before:

```
ESX.RegisterServerCallback('esx_policejob:storeNearbyVehicle', function(source, cb, nearbyVehicles)
local xPlayer = ESX.GetPlayerFromId(source)
local foundPlate, foundNum

	for k,v in ipairs(nearbyVehicles) do
		local result = MySQL.Sync.fetchAll('SELECT plate FROM owned_vehicles WHERE owner = @owner AND plate = @plate AND job = @job', {
			['@owner'] = xPlayer.identifier,
			['@plate'] = v.plate,
			['@job'] = xPlayer.job.name
		})

		if result[1] then
			foundPlate, foundNum = result[1].plate, k
			break
		end
	end
```

Then again we change

`  ['@owner'] = xPlayer.identifier,`

into

`  ['@owner'] = 'society:' .. xPlayer.job.name, `

With this last change we will be able to put police society vehicles into the garage and take them out.

BTW, some important notes:

1. I'm no expert on ESX and/or LUA, I just started with both like a week ago. However, I do have experience on other programming languages and SQL.
2. This is a personal "patch". I made it for my personal server but I do think there are great chances it should work on other servers. I look forward to hearing about it.
3. If esx_vehicleshop and esx_policejob coders feel like they need to use this just go ahead and do it. Have fun!

**Comment by ElPumpo** [comment]
We are not intrested in the "society vehicles" concept.

**Comment by jamie543** [comment]
Why would this not use the society vehicle concept why would an individual police officer own the vehicle it would make more sense for the Police department to own the vehicle and the vehicles shared amongst the officers and for the Boss to be responsible for buying more vehicles as and when the department grows.

**Comment by DonKKijotE** [comment]
> Why would this not use the society vehicle concept why would an individual police officer own the vehicle it would make more sense for the Police department to own the vehicle and the vehicles shared amongst the officers and for the Boss to be responsible for buying more vehicles as and when the department grows.

I agree :)

**Comment by ElPumpo** [comment]
Implement it yourself.

**Comment by zabattaro** [comment]
@DonKKijotE Excelent idea!
