### ISSUE TITLE
how to just rent free police cars

### ISSUE THREAD

**Issue by SliderKP** [ESX-Org/esx_policejob#307]
i want if possible, how to rent police cars, and not selling to polices... it does not make sense, when they stop being police they continue with the vehicles

**Comment by protaknium** [comment]
Use this version! https://github.com/ESX-Org/esx_policejob/tree/1.2.0

**Comment by adaoraul** [comment]
I'm adding society cars for the police and ambulance jobs. Makes more sense if the cars belongs to the corporation
