### ISSUE TITLE
Critical => Big Bug in player management 

### ISSUE THREAD

**Issue by Blackwave78** [ESX-Org/esx_policejob#309]
Big Bug in player management when you open this menu =>

https://i.imgur.com/l76oeVg.jpg

if open it's imposible to click on the buttons and need to leave the game for debug player

**Comment by mamadlooloo** [comment]
Edit your server.cfg.
Put the esx_society at the top of the esx_policejob.
--------------------------
start esx_society
start esx_policejob
--------------------------

**Comment by Blackwave78** [comment]
Same isue this is change nothing

**Comment by Blackwave78** [comment]
I think that the esx_society script is completely buggy I even reinstall the server completely I have the same error, but it is impossible to send a request because it is blocked on their git

**Comment by Blackwave78** [comment]
My bad , mod for menu bugged, i fix it ,re-install esx_menu_default ... menu-list ... menu-dialog
