### ISSUE TITLE
Armory 

### ISSUE THREAD

**Issue by BuLLeTLG** [ESX-Org/esx_policejob#310]
Buy weapons can't seem to work , I have everything up to date , all the other menus are working fine,  only buy weapons and is not giving me any error

**Comment by LeCyreaxYT** [comment]
For those of you still having this issue, I received great help in fixing this from the community on the ESX Discord by (Sojobo).

To fix this, you need to add this code to: es_extended\shared\functions.lua

``ESX.GetWeapon` = function(weaponName)
    weaponName = string.upper(weaponName)
    local weapons = ESX.GetWeaponList()

    for i=1, #weapons, 1 do
        if weapons[i].name == weaponName then
            return i, weapons[i]
        end
    end
end`

**Comment by BuLLeTLG** [comment]
I don't have that anymore , they updated that so idk why is not working

**Comment by mamadlooloo** [comment]
nice, work for me
thanksssss
----------------------------
To fix this, you need to add this code to: es_extended\shared\functions.lua
https://pastebin.com/bczuAG92
