### ISSUE TITLE
Uncuff

### ISSUE THREAD

**Issue by xandoriax** [ESX-Org/esx_policejob#317]
I Updated to latest version of ESX_Policejob and i can no longer uncuff people, is there an easy way of fixing this
basically people get frozen in place when you uncuff them and it looks like handcuffs are still on (Person will be able to punch, move(in same spot) and jump but looks as if they were handcuffed and cannot move from the position they are in)

Simply talking,
Cuffing works
Uncuffing makes people freeze in place and unable to move

**Comment by Madogi** [comment]
Fix in pull requests
