### ISSUE TITLE
PLEASE HELP ME!!!

### ISSUE THREAD

**Issue by Hkoyuer** [ESX-Org/esx_policejob#321]
When starting the server I get this error please help me!:

Error parsing script @esx_policejob/locales/en.lua in resource esx_policejob: @esx_policejob/locales/en.lua:4: unexpected symbol near '<\194>

**Comment by flowdevLOL** [comment]
delete en.lua or simply fix the syntax error

**Comment by Hkoyuer** [comment]
But I don't know how to fix it, can you help me?

**Comment by flowdevLOL** [comment]
What language are you using ?

**Comment by flowdevLOL** [comment]
Show me en.lua

**Comment by Hkoyuer** [comment]
https://pastebin.com/K8NfUSev

**Comment by flowdevLOL** [comment]
![image](https://user-images.githubusercontent.com/48724807/59429909-1c17f180-8de1-11e9-9232-f82f9792ec20.png)
No errors on my side

**Comment by Hkoyuer** [comment]
hmm why do i have the error then?

**Comment by flowdevLOL** [comment]
[prout.zip](https://github.com/ESX-Org/esx_policejob/files/3285801/prout.zip)

**Comment by Hkoyuer** [comment]
now it works thank you very much
