### ISSUE TITLE
Unpaid Bills Issue

### ISSUE THREAD

**Issue by polarim** [ESX-Org/esx_policejob#331]
When trying to check unpaid bills, it will open the menu when individuals do not have any fines, but when they do; nothing opens.  I get an 'error' I think, related to unable to index a nil value on line :1075 of police client script though. 

I'll be trying to fix it otherwise, but maybe someone here knows how if they've run into it.

**Comment by Duqino** [comment]
im having the same issue only no error in console

**Comment by Moldrok** [comment]
> When trying to check unpaid bills, it will open the menu when individuals do not have any fines, but when they do; nothing opens. I get an 'error' I think, related to unable to index a nil value on line :1075 of police client script though.
> 
> I'll be trying to fix it otherwise, but maybe someone here knows how if they've run into it.

Did you fix it man? how?

**Comment by polarim** [comment]
Fixed it; error was actually on line 1079
billId = bills[i].id

change it to billId = bills[k].id

**Comment by Moldrok** [comment]
> Fixed it; error was actually on line 1079
> billId = bills[i].id
> 
> change it to billId = bills[k].id

good work man!
