### ISSUE TITLE
Can't change clothes as cop

### ISSUE THREAD

**Issue by Rogaar** [ESX-Org/esx_policejob#339]
When I try to change those in the locker room is receive an error in the console.

es_extended: TriggerServerCallback =>  [esx_service:isInService] does not exist

It happens when I press enter on the uniform I wish to change into. Changing to other job uniforms works fine.

**Comment by Rogaar** [comment]
never mind. I figured it out. it was the esx_service mod that was needed even though it wasn't listed a dependency. found it on another post shortly after posting this one. spent the last 6 hours trying to fix this.

**Comment by Raydiaa** [comment]
I have esx_ service and for some reason, I cant put uniforms on :/
