### ISSUE TITLE
Stuck in police vehicle shop. attempt to index a nil value (local 'garage')

### ISSUE THREAD

**Issue by ipodtouchdude** [ESX-Org/esx_policejob#343]
I am stuck in the vehicle shop whem I try to navigate the menu trying to buy a car.
I am getting: 
`SCRIPT ERROR: @esx_garage/client/main.lua:299: attempt to index a nil value (local 'garage')`
`> fn (@esx_garage/client/main.lua:424`
`SCRIPT ERROR: @esx_garage/client/main.lua:299: attempt to index a nil value (local 'garage')`
`> fn (@esx_garage/client/main.lua:439`

Not sure if it is esx_garage or esx_policejob as it is in the police vehicle shop

**Comment by meotobungbu** [comment]
> I am stuck in the vehicle shop whem I try to navigate the menu trying to buy a car.
> I am getting:
> `SCRIPT ERROR: @esx_garage/client/main.lua:299: attempt to index a nil value (local 'garage')`
> `> fn (@esx_garage/client/main.lua:424`
> `SCRIPT ERROR: @esx_garage/client/main.lua:299: attempt to index a nil value (local 'garage')`
> `> fn (@esx_garage/client/main.lua:439`
> 
> Not sure if it is esx_garage or esx_policejob as it is in the police vehicle shop

Chảnge : InsideShop = vector3(228.5, -993.5, -99.5),

**Comment by meotobungbu** [comment]
> > I am stuck in the vehicle shop whem I try to navigate the menu trying to buy a car.
> > I am getting:
> > `SCRIPT ERROR: @esx_garage/client/main.lua:299: attempt to index a nil value (local 'garage')`
> > `> fn (@esx_garage/client/main.lua:424`
> > `SCRIPT ERROR: @esx_garage/client/main.lua:299: attempt to index a nil value (local 'garage')`
> > `> fn (@esx_garage/client/main.lua:439`
> > Not sure if it is esx_garage or esx_policejob as it is in the police vehicle shop
> 
> Chảnge : InsideShop = vector3(228.5, -993.5, -99.5),

delete 

		--{ model = 'police', label = 'Police Cruiser', price = 1000 }, --<  stuck here
		{ model = 'pbus', label = 'Police Prison Bus', price = 5000 },
		{ model = 'police3', label = 'Police Interceptor', price = 10000 },
		{ model = 'policet', label = 'Police Transporter', price = 18500 },
		{ model = 'policeb', label = 'Police Bike', price = 30500 },
		{ model = 'riot', label = 'Police Riot', price = 70000 },
		{ model = 'fbi2', label = 'FIB SUV', price = 60000 }
