### ISSUE TITLE
Dead Player duplication

### ISSUE THREAD

**Issue by SaadGustavo** [ESX-Org/esx_policejob#344]
When someone is Dead and you try to take from him his Weapon its duplicating

**Comment by XvenDeR** [comment]
found solution?

**Comment by SaadGustavo** [comment]
Yeah found it its coming from es_extended you must delete some lines .

**Comment by SaadGustavo** [comment]
Found it again for you man <3 

https://github.com/ESX-Org/es_extended/pull/322/commits/2e39e3d01a79d246738be266f8cad390767bad1c
