### ISSUE TITLE
error store item

### ISSUE THREAD

**Issue by merder123** [ESX-Org/esx_policejob#345]
SCRIPT ERROR: @esx_addoninventory/server/classes/addoninventory.lua:39: attempt to index a nil value (global 'Items')
> ref (@esx_addoninventory/server/classes/addoninventory.lua:39)
> ref (@esx_policejob/server/main.lua:175)
> handler (@esx_addoninventory/server/main.lua:86)
> handler (@esx_policejob/server/main.lua:174)

**Comment by blackcould45** [comment]
same with me anyone can help ?

**Comment by Alevhovic** [comment]
Same here

**Comment by blackcould45** [comment]
pls help

**Comment by chinduwho** [comment]
Im having a similar issue Im looking around in my SQL datebase for like a GUNS list that it should be taking it from but nothings there. my erros when trying to open the BUY WEPON feature is SCRIPT ERROR: @esx_policejob/server/main.lua:282: attempt to index a nil value (local 'store')
> ref (@esx_policejob/server/main.lua:282)
> handler (@esx_datastore/server/main.lua:106)
> ref (@esx_policejob/server/main.lua:280)
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:88)
