### ISSUE TITLE
F6 Menu randomly stops working

### ISSUE THREAD

**Issue by RandomZFx** [ESX-Org/esx_policejob#349]
The menu works fine when you first start up the server but after a 30 minutes or a hour it doesnt want to open. It starts working again after you restart the script.

**Comment by mms84** [comment]
I have the same issue tho mine is when a cop dies. After he is revived, he can't use his F6 menu. I have no idea why that is.

**Comment by RandomZFx** [comment]
Found issue. Remove all isDead statement. For some reason it bugs out when revived

**Comment by whazza1983** [comment]
esx_policejob\client\main.lua

AddEventHandler('esx:onPlayerDeath', function(data)
	isDead = true
end)

to

AddEventHandler('esx:onPlayerDeath', function(data)
	isDead = false
end)
