### ISSUE TITLE
Very high torque

### ISSUE THREAD

**Issue by alex070609** [ESX-Org/esx_policejob#350]
Hi,

I have a problem with your most recent update all my cop cars have very high torque and i don't know how to fix it if any ideas

thx

**Comment by alex070609** [comment]
Yeah i found it inside This file i Just forget to close the thread thx 😁😁

**Comment by HumanTree92** [comment]
U said u found it inside this file. R u talking about esx_policejob and if so what does the code look like.

**Comment by alex070609** [comment]
No inside the handling.meta file i Just tweaked it with my stream folder to act like i wanted, also i have à friend that have the old version of This script and inside the config.lua there are lignes that you can modify to your taste to tweak the cars
