### ISSUE TITLE
Vehicle impossible to pay

### ISSUE THREAD

**Issue by AmbTAlpha** [ESX-Org/esx_policejob#351]
Hello already sorry for my English horrible good voila I install your esx_policejob but when we want to get out a car we are told that can not basically even if I have money nothing that passes I change the price to 0 and still nothing could you help me thank you

**Comment by HumanTree92** [comment]
U know the vehicle price can't be set to 0. Set it to like 1.

**Comment by ElPumpo** [comment]
If the price is 1 then you might as well not use this code..?
