### ISSUE TITLE
Error esx garage

### ISSUE THREAD

**Issue by kzenoxx** [ESX-Org/esx_policejob#377]
Hello I installed the esx_police job in 1.2.0 version but when I want to buy a car the menu disapeared and I am stuck, I have these error in my F8 menu : SCRIPT ERROR: @esx_garage/client/main.lua:274 :attempt to index a nil value (loacal 'garage') 
> fn (@esx_garage/client/main.lua:432)
and : SCRIPT ERROR: @esx_garage/client/main.lua:299: attempt to index a nil value (lolcal 'garage')
> (@esx_garage/client/main.lua:439 )
I need help please 😫
Thanks

**Comment by kzenoxx** [comment]
Oops sorry 1.3.0 version ^^

**Comment by Cactusje** [comment]
Make sure your garage script is up-to-date and that you have ALL depencies including the ones for the garage installed.
