### ISSUE TITLE
Old Garage implement issue

### ISSUE THREAD

**Issue by Cactusje** [ESX-Org/esx_policejob#378]
Hello,

I have been trying to implement the OLD police garage! However I am running into an issue. The code below is the code that should make the garage work. If I open the garage, it'll show all vehicles perfectly fine. But when I spawn them it says the following:

SCRIPT ERROR: @esx_policejob/client/main.lua:298: attempt to index a nil value (global ' vehicles' )

` x = vehicles[partNum].SpawnPoint.x,
                  y = vehicles[partNum].SpawnPoint.y,
                  z = vehicles[partNum].SpawnPoint.z`

This basically means it doesnt understand the part where it's going to spawn the vehicle.
Can anyone help me with this? It needs to understand the newer configuration from esx_policejob. I did try to look into the new code, but since that works with retrieveJobVehicles it's not really clear for me on how to solve it.

`function OpenVehicleSpawnerMenu(station, partNum)

  ESX.UI.Menu.CloseAll()

	local elements = {}

	local sharedVehicles = Config.AuthorizedVehicles.Shared
	for i=1, #sharedVehicles, 1 do
		table.insert(elements, { label = sharedVehicles[i].label, model = sharedVehicles[i].model})
	end

	local authorizedVehicles = Config.AuthorizedVehicles[PlayerData.job.grade_name]
	for i=1, #authorizedVehicles, 1 do
		table.insert(elements, { label = authorizedVehicles[i].label, model = authorizedVehicles[i].model})
	end

    ESX.UI.Menu.Open(
      'default', GetCurrentResourceName(), 'vehicle_spawner',
      {
        title    = _U('vehicle_menu'),
        align    = 'top-left',
        elements = elements,
      },
      function(data, menu)

        menu.close()

        local model = data.current.model

        if not DoesEntityExist(vehicle) then

          local playerPed = PlayerPedId()

          if Config.MaxInService == -1 then

            ESX.Game.SpawnVehicle(model, {
              x = vehicles[partNum].SpawnPoint.x,
              y = vehicles[partNum].SpawnPoint.y,
              z = vehicles[partNum].SpawnPoint.z
            }, vehicles[partNum].Heading, function(vehicle)
              TaskWarpPedIntoVehicle(playerPed,  vehicle,  -1)
              SetVehicleMaxMods(vehicle)
            end)

          else

            ESX.TriggerServerCallback('esx_service:enableService', function(canTakeService, maxInService, inServiceCount)

              if canTakeService then

                ESX.Game.SpawnVehicle(model, {
                  x = vehicles[partNum].SpawnPoint.x,
                  y = vehicles[partNum].SpawnPoint.y,
                  z = vehicles[partNum].SpawnPoint.z
                }, vehicles[partNum].Heading, function(vehicle)
                  TaskWarpPedIntoVehicle(playerPed,  vehicle,  -1)
                  SetVehicleMaxMods(vehicle)
                end)

              else
                ESX.ShowNotification(_U('service_max', inServiceCount, maxInService) .. inServiceCount .. '/' .. maxInService)
              end

            end, 'police')

          end

        else
          ESX.ShowNotification(_U('vehicle_out'))
        end

      end,
      function(data, menu)

        menu.close()

        CurrentAction     = 'menu_vehicle_spawner'
        CurrentActionMsg  = _U('vehicle_spawner')
        CurrentActionData = {station = station, partNum = partNum}

      end
    )

end`

**Comment by Cactusje** [comment]
Solved

**Comment by Worryinglamb08** [comment]
Could you share the solution with me please?

**Comment by Cactusje** [comment]
I will send you all the things to change tommorow.

**Comment by Worryinglamb08** [comment]
> I will send you all the things to change tommorow.

Alright, appreciate it

**Comment by Worryinglamb08** [comment]
Hi, any update? @Cactusje

**Comment by Goontje** [comment]
> Solved

Can you please contact me so i can update this aswell, i hate the policejob 1.3 vehicle spawn method.
