### ISSUE TITLE
My Police armory isnt working.

### ISSUE THREAD

**Issue by SyncLv** [ESX-Org/esx_policejob#381]
The police shop, that you open by pressing [e] doesnt open and my locker where you change your clothes doesnt either... tried to change disc-inventoryhud and update the esx_policejob, but still nothing! Even updated the requirements... Any help i could get?!

**Comment by Cactusje** [comment]
Are you having issues with opening the menu or getting the actual weapons out, if so I can't help you since I also have an issue open for it #382 

If you can't get the menu open:
- Make sure es_extended, EssentialMode & all depencies are up-to-date
- Add a print to the event to make sure it runs.
