### ISSUE TITLE
"Search", "ID Card", "Manage License" doesnt work anymore

### ISSUE THREAD

**Issue by GianmarcoAquilano** [ESX-Org/esx_policejob#383]
As the tiltle, these options in the F6 menu doesnt work anymore, no errors in console, the functions can detect if there is a closestplayer but the menu doesnt show up. Am I the only? 
Tried with "old" and last es_extended

**Comment by Tiimon** [comment]
Yep, I am currently having this issue as well :(

**Comment by J0K3RY-03** [comment]
I also have this problem, a solution ?

**Comment by Tiimon** [comment]
Does not to seem to be a fix currently, I saw that they were working on a new search UI so maybe it'll fix this issue?

**Comment by Tiimon** [comment]
Can you send me version 1.2?

**Comment by J0K3RY-03** [comment]
https://github.com/ESX-Org/esx_policejob/releases/tag/1.2.0

**Comment by Tiimon** [comment]
Yeah seems to work for me as well, this has to be a 1.3 issue, don't understand why this card was closed

**Comment by ElPumpo** [comment]
Closed because it does work and all of you managed to break it yourselves

**Comment by jok3ry** [comment]
You say it works but I have not touched any file, it is a completely new installation and all the prerequisites are installed so I would have to tell me how I could have broken it if I didn’t touch anything more. . Explain to us what we could do.

**Comment by ElPumpo** [comment]
Update esx and identity

**Comment by Tiimon** [comment]
Is esx_identity required for searching? I don't run identity and never have. 1.2 works perfectly fine on my server without identity, all my other dependencies and any scripts I run are all the most recent files.

**Comment by ElPumpo** [comment]
Then disable identity code

**Comment by J0K3RY-03** [comment]
Have you managed to make it work because it still does not work everything is up to date these are all the latest files released same identity everything is new so it may not come from my home I am sorry but it is impossible I have nothing could break while version 1.2 works well and I did not want to use cetye version

**Comment by Tiimon** [comment]
I've gone through and disabled all the identity code and still no luck getting searching to work. With the number of people expressing concerns over it being either bugged out or not working you should at least take a look. 
When I try to search and there's no player nearby I get the message "no players nearby" but when someone is nearby nothing happens no console errors or in-game.

**Comment by TheNoobie-code** [comment]
Still not working
