### ISSUE TITLE
Addon Vehicle Null

### ISSUE THREAD

**Issue by dracuslayer** [ESX-Org/esx_policejob#386]
i use custom add on vehicles. i created a vehicle_names.lua with my hashs in place. but vehicles are still showing up as null on the shop menu and stored vehicle menu.

**Comment by ElPumpo** [comment]
You are doing it wrong then

**Comment by dracuslayer** [comment]
no i do know i did it right. is this not the right way to make a vehicle_names.lua 
`function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
  AddTextEntry('0xF4CD35B7', '2011 Crown Vic')
end)`

**Comment by HumanTree92** [comment]
Yeah that doesn't look right. Try this instead
```lua
function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	-- Example: AddTextEntry('yacht2', 'Sea Ray L650')
	AddTextEntry('model_name_here', 'vehicle_name_here')
end)
```
