### ISSUE TITLE
Boss menu error

### ISSUE THREAD

**Issue by Aaronh0103** [ESX-Org/esx_policejob#389]
Hey guys, I’m having an issue with the esx_policejob’s Boss Menus. So when I press E to get into the boss menu blip at Mission Row, immediately in my TXadmin console I receive the following message: “esx_society: steam:xxxx attempted open a society boss menu!” and it doesn’t open. Does anyone know what I did wrong? The database has the police as the job name and boss as the grade and is reflected also in the client/main.lua file. Been racking my brain for a few days and am probably overthinking it.

**Comment by ElPumpo** [comment]
See https://github.com/ESX-Org/esx_society/blob/c64b2b078f0d438bcf595281cddd973f6d93412c/server/main.lua#L344 to why this happens. Your highest grade in the job **must be** `boss`

**Comment by Aaronh0103** [comment]
Thank you! So If I wanted to add additional job_grades to the actual job to have access to the boss menu, would I do a:

“if xPlayer.job.name == job and xPlayer.job.grade_name == 'boss' or ‘custom_name1’ or ‘custom_name2’ then” 

or would I need to do an 
“elseif xPlayer.job.name == job and xPlayer.job.grade_name == 'custom_name1’ then

elseif xPlayer.job.name == job and xPlayer.job.grade_name == 'custom_name2' then” inside of esx_society and esx_policejob client/main.lua?

**Comment by ElPumpo** [comment]
Not supported at this time, you'll have to modify the code I linked..

**Comment by Aaronh0103** [comment]
Ok gotcha. Thank you for your time and support! 😄
