### ISSUE TITLE
Cannot open vehicles menu

### ISSUE THREAD

**Issue by Mayro176** [ESX-Org/esx_policejob#390]
Hello.. i am currently having problem with police job, closely with car garage, when i press to enter garage, it writes me an error 

> SCRIPT ERROR: @esx_policejob/client/vehicle.lua:18: attempt to index a nil value (field "?")
> ref (@esx_policejob/client/vehicle.lua:18)
> callback (esx_menu_default/client/main.lua:50)

I have added some vehicles in config, and havent tested it before it, could it be the case?

**Comment by GingeeEly2016** [comment]
i have the same problem did you sort it out ?

**Comment by Raydiaa** [comment]
Any fix?
