### ISSUE TITLE
Helicopter Menu will not open

### ISSUE THREAD

**Issue by Aaronh0103** [ESX-Org/esx_policejob#392]
Hello I am currently having an issue with the police job's, Helicopter Vehicle Shop. When I try to enter the shop, it gives me an error:

    SCRIPT ERROR: @esx_policejob/client/vehicle.lua:18: attempt to index a nil value (field "?")
    ref (@esx_policejob/client/vehicle.lua:18)
    callback (esx_menu_default/client/main.lua:53)
error during NUI callback menu_submit: citizen:/scripting/lua/scheduler.lua807: bad argument #1 to 'unpack' (table expected, got nil)
 
I can access the "Open Garage" and "Store Vehicle in Garage" without any errors. Any help is much appreciated!

**Comment by ElPumpo** [comment]
It works just fine, your ranks are missing in the config file

**Comment by Aaronh0103** [comment]
![7CDC7490-7995-4E2C-88C3-F3FFF3D02710](https://user-images.githubusercontent.com/42502532/73927557-742ac900-4886-11ea-8bc4-abda4eee3c70.png) I must be missing something else, because I kept the ranks for the helicopters the same.
