### ISSUE TITLE
Worry identity card and search players with the new version 1.3

### ISSUE THREAD

**Issue by J0K3RY-03** [ESX-Org/esx_policejob#394]
Worry identity card and search players with the new version 1.3 here I try to search and look at the identity card but impossible nothing happens I have no error in the console or F8 I tried use an old version extended its does not work either then I try the version 1.2 of policejob and its works so the problem comes from version 1.3 could we see a fix? thank you for your work.

**Comment by pavpd** [comment]
Have you found a fix? Nobody seems to help here so could you?
