### ISSUE TITLE
Config.lua error

### ISSUE THREAD

**Issue by hiphoprexx** [ESX-Org/esx_policejob#395]
Hi there!

So I edited the new config.lua and now I'm getting this error in console :

Creating script environments for esx_policejob
Error parsing script @esx_policejob/config.lua in resource esx_policejob: @esx_policejob/config.lua:160: '}' expected (to close '{' at line 129) near '{'
Failed to load script config.lua.
Error loading script server/main.lua in resource esx_policejob: @esx_policejob/server/main.lua:5: attempt to index a nil value (global 'Config')
stack traceback:
@esx_policejob/server/main.lua:5: in main chunk
Failed to load script server/main.lua.
Started resource esx_policejob

Config.lua attached

Regards,
[config (1).zip](https://github.com/ESX-Org/esx_policejob/files/4175482/config.1.zip)

**Comment by DerNotdienst112** [comment]
I have the same problems, after a edit in the config.lua
