### ISSUE TITLE
The y search ID Card system does not work

### ISSUE THREAD

**Issue by m0iises19** [ESX-Org/esx_policejob#396]
The y search ID Card system does not work.

Any solution?

**Comment by J0K3RY-03** [comment]
Ha well we are more and more to have the worry we say that it is we who have broken the script while all the files that I have put are new and ALL UPDATED so it's not from us.

**Comment by m0iises19** [comment]
I just put an old version of esx_policejob and everything is going well and in this new one no ...

**Comment by J0K3RY-03** [comment]
And I just put the new version in an old database with the NOT UP TO DATE files and it works and with ALL UPDATE files it doesn't work looking for the error? I do not want to release a database with old files just for police work

**Comment by m0iises19** [comment]
is that the thing is that there is no sale error, only that the action does not open

**Comment by J0K3RY-03** [comment]
Yes but now you have to find WHY its does not open especially since all the files are up to date is to understand nothing.

**Comment by J0K3RY-03** [comment]
If you have the solution I would be glad to have it too.

**Comment by m0iises19** [comment]
I don't know if I will have an answer to this, they banned me from the discord without doing anything ... just for asking about this error
