### ISSUE TITLE
Search  and ID card does not work

### ISSUE THREAD

**Issue by tajangi** [ESX-Org/esx_policejob#399]
I can't search or get a person ID card
But I can do with the esx_Mafia or esx_Gang script

**Comment by tajangi** [comment]
why ??????

**Comment by ElPumpo** [comment]
It does work

**Comment by tajangi** [comment]
When I click on Search, nothing happens

**Comment by tajangi** [comment]
Help me instead of blocking!

**Comment by Kretena1** [comment]
Doesn't work for me too.
