### ISSUE TITLE
Body Search does not work.

### ISSUE THREAD

**Issue by eltsufin** [ESX-Org/esx_policejob#400]
Player body search does not work. If i press the button in meny "body search" anything happens..
And Id check does not to anythin. Everythig works fine but these.. not work. I need fast help.

**Comment by Tiimon** [comment]
There's a few of us that have been having this problem, but the OP just closed the card. I hope there's a fix soon

**Comment by tajangi** [comment]
In older versions of esx_policejob and es_extended this may be correct!
Has anyone tried it?

**Comment by m0iises19** [comment]
in previous versions everything is going well, in this new one not

**Comment by tajangi** [comment]
> in previous versions everything is going well, in this new one not

What versions(esx_policejob  & es_extended ) do you use?

**Comment by m0iises19** [comment]
I have the latest versions of everything installed and I have this error

**Comment by Tiimon** [comment]
I do as well. I'm currently running police 1.2 with the newest version of extended, no issues at all. The issue lies within police 1.3

**Comment by eltsufin** [comment]
So i have to go back to old version?

**Comment by Tiimon** [comment]
Yes just use 1.2 for the time being.

**Comment by eltsufin** [comment]
Good

**Comment by J0K3RY-03** [comment]
The creator says that it comes from us but there are several of us who have this problem so sometimes you have to know how to question yourself and check because if several people report the problem it is that there is really a problem and stop saying that it is the fault of others

**Comment by m0iises19** [comment]
there are more people complaining about that problem, the creator came to ban me from the discord for asking him about this problem ...

**Comment by Tiimon** [comment]
Not surprised, he's banned multiple people for petty reasons. ESX is a great framework to build around but the support isn't at all.

**Comment by m0iises19** [comment]
but what can we do? If the creator tells us that it is our problem, and for example I have everything installed to the latest version and it is not going well. Apart from that I created a server from scratch with esx_policejob and the requirements and still it still gives me the same error of not being able to cache or see your ID and also not see the licenses

**Comment by polarim** [comment]
#404
