### ISSUE TITLE
Search Adjustment

### ISSUE THREAD

**Issue by NickRobinYT** [ESX-Org/esx_policejob#417]
Is there any way to make it so that when searching and taking something from someone it doesn't put it in your inventory?

**Comment by XvenDeR** [comment]
Yes, in server.lua if you understand a little of it you will find it.

**Comment by NickRobinYT** [comment]
![image](https://user-images.githubusercontent.com/29695470/78321194-518cf780-7539-11ea-9466-fd09d2df2076.png)
What would I remove?

**Comment by HumanTree92** [comment]
For `item_standard` comment out by doing -- in front of
sourceXPlayer.addInventoryItem   (itemName, amount)

For `item_account` comment out by doing -- in front of
sourceXPlayer.addAccountMoney   (itemName, amount)

For `item_weapon` comment out by doing -- in front of
sourceXPlayer.addWeapon   (itemName, amount)

**Comment by NickRobinYT** [comment]
> For `item_standard` comment out by doing -- in front of
> sourceXPlayer.addInventoryItem (itemName, amount)
> 
> For `item_account` comment out by doing -- in front of
> sourceXPlayer.addAccountMoney (itemName, amount)
> 
> For `item_weapon` comment out by doing -- in front of
> sourceXPlayer.addWeapon (itemName, amount)

Thank you so much
