### ISSUE TITLE
Boss Interactions bug?

### ISSUE THREAD

**Issue by FBFezz** [ESX-Org/esx_policejob#426]
I have the Player Management enabled, changed the boss name in database, config and in the main where it calls the job grade name. I am able to see the icon for it but when I press e over at it nothing happens. no errors in client or server console it just says 

esx_society: (Steam id) attempted open a society boss menu!

**Comment by Jailmate** [comment]
It doesn't appear you have ingested the SQL file. Look for the esx_police.sql file and read the instructions.

**Comment by FBFezz** [comment]
I have, i also re did it about 3 times but to no avail

**Comment by Jailmate** [comment]
Did you add society_police to your addon_account in the SQL?

**Comment by FBFezz** [comment]
Yes its in the addon acount table in the db

**Comment by Jailmate** [comment]
Ok and lastly, you assigned your PED the rank to which name=boss is assigned right?

**Comment by FBFezz** [comment]
Yep

**Comment by Jailmate** [comment]
Ok send your config.lua and client/main.lua into here, and also a screenshot of your job grades.

**Comment by FBFezz** [comment]
Ok give me a few minutes

**Comment by FBFezz** [comment]
https://prnt.sc/s0peia

https://prnt.sc/s0pf4e


[esx_policejob.zip](https://github.com/ESX-Org/esx_policejob/files/4488962/esx_policejob.zip)

**Comment by Jailmate** [comment]
Those screenshots - I don’t see a grade where you have assigned a grade that has the name boss?

**Comment by FBFezz** [comment]
In the old version i was able to change "boss" to "gold" and it worked fine but not anymore

**Comment by Jailmate** [comment]
I would suggest reverting  gold back to boss, there are too many dependencies that require the name to be ‘boss’ unless you want to start customising it to suit your server setup

**Comment by FBFezz** [comment]
Just realised i can just change the label in database instead of keeping it boss, ill try it and let you know

**Comment by Jailmate** [comment]
Ok, but changing the ‘label’ in your SQL won’t change the outcome. You need to change one of the grade’s ‘name’ column in your sql to ‘boss’. Otherwise the script won’t recognise the grade as boss and therefore allow the rank holders access the boss menu.

**Comment by FBFezz** [comment]
Yeah im changing it in the script as well as SQL, was mainly so it didn't just say boss instead of gold command.

**Comment by FBFezz** [comment]
Ah yeah that worked, thanks for the help and sorry to disturb you, you can close this now
