### ISSUE TITLE
Armory not letting me buy weapons

### ISSUE THREAD

**Issue by FBFezz** [ESX-Org/esx_policejob#429]
Hello again, sorry for interupting you again but for some reason cannot open the armoury anymore, i do have access and this is the error (happens with fresh installs as well) 

https://prnt.sc/s1n0n3

**Comment by eltsufin** [comment]
I have same!
But i get this error:
![image](https://user-images.githubusercontent.com/36920086/79689103-505b0a80-825b-11ea-8f4a-7092a3a4210a.png)
