### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by PoortlandRP** [ESX-Org/esx_policejob#436]
Hello, I am using the new es extended and the new esx_policejob. Only somehow I can't search anyone and can't belong to anyone and / or see her ID card this is really annoying and I'm not getting it fixed I hope you can help me.

**Comment by Fluffyss** [comment]
How did you fix it? Me and several others are having the same issue.

**Comment by PoortlandRP** [comment]
esx_optionalneeds
