### ISSUE TITLE
[Bug] Search and ID 

### ISSUE THREAD

**Issue by FBFezz** [ESX-Org/esx_policejob#461]
Search and Id dont work but are not giving me any errors in either F8 or rcon. Hacnt edited the script apart from enabling some things to true and its a fresh install of the server

**Comment by SergitoKLK** [comment]
The same thing happens to me, did you find a solution?

**Comment by FBFezz** [comment]
Nope, think it might be because esx_identity requires policejob as a dependency but its also a dependency for policejob

**Comment by SergitoKLK** [comment]
I found this but I doubt it is our problem since it talks about another scrip connected to the police, then later I will start editing the code to see if I can solve it, in that case, I will pass the file to you so that you do not have the problem either

sorry for my English

https://github.com/ESX-Org/esx_policejob/issues/418

**Comment by SergitoKLK** [comment]
In fact right now, I have just edited a small part of the code and it does not give me an error, when I have a friend available I will test if it works, if it works correctly I will pass it to you

Greetings  :D

**Comment by FBFezz** [comment]
Yeah im testing as well and thanks for the help :D Also are you using the latest esx_identity?

**Comment by SergitoKLK** [comment]
I already tried and it didn't work

If I am using the latest esx_identity, since the previous ones are not compatible with this version of es_extended

**Comment by FBFezz** [comment]
Do oyu not have the issue that it keeps coming back even after you made your character? for sex identity and hmm will look further into this when i sleep

**Comment by SergitoKLK** [comment]
How? That when you disconnect you appear with the default skin?

If you have that problem the only solution is leaving FiveM, not the FiveM menu

**Comment by FBFezz** [comment]
No so you know when you first join a server and it says Name and dob and height. That comes up every time i join the server and i cant find the fix

**Comment by SergitoKLK** [comment]
Try to restore the esx_indentity database, that is, to delete it and put the sql back, if not, reset the entire database, once you put the es_Extended put the esx_identity first

**Comment by FBFezz** [comment]
Tried both and none worked but tis fine i opened up an issue on the github

**Comment by SergitoKLK** [comment]
Are you using the new version?

**Comment by FBFezz** [comment]
Yep

**Comment by rafaelm71** [comment]
@SergitoKLK Do you fix the bug? I have a headache trying to fix it :(

**Comment by FBFezz** [comment]
So its not hte idetntity problem but i think this might have to do with something?

![image](https://user-images.githubusercontent.com/43589668/82979200-5ffa0b80-9fde-11ea-97b1-5616f2307eaf.png)


Should that not be data.dateofbirth as that's what its called in identity

**Comment by SergitoKLK** [comment]
I still have that problem

**Comment by FBFezz** [comment]
Fixed it here https://github.com/ESX-Org/esx_policejob/pull/404 but bac doesnt show for some reason now

**Comment by MoonDawnGames** [comment]
I got the same issue. No fix unfortunately!

**Comment by yaniskyblue** [comment]
Hi! try using esx_optionalneeds or comment this lines in server/main : 
TriggerEvent('esx_status:getStatus', target, 'drunk', function(status)
			if status then
				data.drunk = ESX.Math.Round(status.percent)
			end
		end)
			if Config.EnableLicenses then
				TriggerEvent('esx_license:getLicenses', target, function(licenses)
					data.licenses = licenses
					cb(data)
				end)
			else
				cb(data)
			end

that works for me

**Comment by FBFezz** [comment]
Fixed it and forgot to close, sorry but appreciate the help

**Comment by MoonDawnGames** [comment]
> Fixed it and forgot to close, sorry but appreciate the help

how did you fix it?

**Comment by FBFezz** [comment]
https://github.com/ESX-Org/esx_policejob/pull/404
