### ISSUE TITLE
Locale `de` does not exist

### ISSUE THREAD

**Issue by Tigerpanzer02** [ESX-Org/esx_policejob#51]
Heey,

I have a problem, when i would like to use it!

It says me INGAME on the Map that the Locale de not exist but why?

**Comment by ElPumpo** [comment]
Because it's missing https://github.com/ESX-Org/esx_policejob/blob/master/__resource.lua#L12

**Comment by Tindergarten** [comment]
Well my latest PR fixes that :)

**Comment by ElPumpo** [comment]
Fixed, closing
