### ISSUE TITLE
Can't use Custom Uniforms

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_policejob#55]
So since the merge of https://github.com/ESX-Org/esx_policejob/pull/36 you can't use custom uniforms. It seemed like before it was easier. If there is a new way to use custom uniforms maybe tell us how b/c i can't figure it out.

**Comment by zarx1337** [comment]
Same issue here.

**Comment by zarx1337** [comment]
How about cones?

**Comment by HumanTree92** [comment]
I switched over to https://github.com/ElPumpo/esx_policejob and put some code in from the original police job. I can now use custom uniforms & vehicles are limited to ranks. Here are my client & server files if you want them. https://pastebin.com/vW0J9rFf & https://pastebin.com/EDjVqP85 There is also a few extra stuff in there like jail, strip, & revive.

**Comment by HumanTree92** [comment]
Also if you have the esx_ambulance job & you want custom uniforms check out my esx_ambulancejob https://github.com/HumanTree92/esx_ambulancejob

**Comment by zarx1337** [comment]
Does the put in vehicle work?

**Comment by HumanTree92** [comment]
I haven't testing anything with Put in Vehicle. However tho yes Objects work but the Cones do not work for me.

**Comment by ElPumpo** [comment]
The uniforms work just fine.
