### ISSUE TITLE
I have found the bug for esx_policejob when placing objects!

### ISSUE THREAD

**Issue by zarx1337** [ESX-Org/esx_policejob#57]
The bug has to do with es_extended and esx_menu_default. I downgraded to an older version of es_extended and using the latest esx_policejob. Everything works fine!

**Comment by ElPumpo** [comment]
Duplicate of #58, closing.

**Comment by zarx1337** [comment]
Why do you close mine I was the one who found the bug? Close #58 instead..

**Comment by ElPumpo** [comment]
Yep I should but the other one has more activity
