### ISSUE TITLE
problems with check license and id 

### ISSUE THREAD

**Issue by Parme89** [ESX-Org/esx_policejob#66]
having issues checking license and ID quite often , on some players it works but on many it doesnt.
no errors in console

**Comment by ElPumpo** [comment]
Well can you show the stack trace, or anything that looks suspicous?

**Comment by Parme89** [comment]
Hola elpumpo! Sorry if im stupid here but i dont get any stack trace when its happening . The console is just plain normal, i think this appeared after i updated esx but i cant go back to an older because the i dont get the new nui changes

**Comment by Parme89** [comment]
Bump

**Comment by itzaudro** [comment]
Bump. I'm having the same issues.

**Comment by Parme89** [comment]
@itzaudro they keep saying the issues is ”not related” so i did fix it myself by setting enablelicenses to false and using a snippet for it instead . You better do that aswell.

**Comment by itzaudro** [comment]
Could you possibly help me out with the snippet thing?

**Comment by nykroza** [comment]
I have the same problem on my server.. If the player doesn't have his license permit the CheckID will never work, but once they have the "StreetCode" in their inventory, everything is working fine.

**Comment by ElPumpo** [comment]
Does this still happen? It might have been caused by a bug if you've not enabled esx identity. The code for checking the drunk status was not correct and was breaking the function.

**Comment by Parme89** [comment]
Dude ive quit fivem long time ago, nice answering time ;) cheers

Mvh Emil Parnestam

28 sep. 2018 kl. 08:33 skrev Samuel <notifications@github.com<mailto:notifications@github.com>>:


Does this still happen? It might have been caused by a bug if you've not enabled esx identity. The code for checking the drunk status was not correct and was breaking the function.
