### ISSUE TITLE
Cop Blips help

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_policejob#67]
Can someone please help me by telling how to use this new Cop Blip System. I have the code all in & everything in the Police Job works. 
Questions:
1. How is this cop blip system different then not having one in. B/c by default without a trainer you can see everyone on the map unless its just me.
2. Is anyone using a Blip system that only shows blips for police.

**Comment by ElPumpo** [comment]
Obviously only cops ultilize this blip system, seriously if you don't have time to read the code then we don't have time to answer your silly questions. And why would you ever have a trainer enabled on a rp server?!
