### ISSUE TITLE
remove the label client/main.lua

### ISSUE THREAD

**Issue by Parme89** [ESX-Org/esx_policejob#69]
couldnt make a PR so ill post here 

please remove this one cus otherwise it shows double if enabled in config =) 

{label = _U('id_card'),         value = 'identity_card'},
          {label = _U('search'),          value = 'body_search'},
          {label = _U('handcuff'),        value = 'handcuff'},
          {label = _U('drag'),            value = 'drag'},
          {label = _U('put_in_vehicle'),  value = 'put_in_vehicle'},
          {label = _U('out_the_vehicle'), value = 'out_the_vehicle'},
          {label = _U('fine'),            value = 'fine'},
      ----->    {label = _U('license_check'),   value = 'license'}
        }
        
        if Config.EnableLicenses then
          table.insert(elements, { label = _U('license_check'), value = 'license' })
        end

**Comment by ElPumpo** [comment]
Haha woops it's fixed now, thanks for being awake / reporting this issue!
