### ISSUE TITLE
The F6 menu does not open at all.

### ISSUE THREAD

**Issue by pastaga164** [ESX-Org/esx_policejob#70]
Hello, I have a problem with policejob, as a police officer can not open the menu F6, yesterday the menu open and close immediately, today I install the new update ESX_Policejob, and the menu F6 no longer opens at all. could you help me ?

Thank you :)

**Comment by Rromdom** [comment]
Hey Pastaga, i had the same problem and solved it this way:

esx_policejob/client

Search for this line:

RegisterNetEvent('esx:setJob')
AddEventHandler('esx:setJob', function(job)
	PlayerData.job = job

and put this BEFORE.
RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
  PlayerData = xPlayer
end)

Example:

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
  PlayerData = xPlayer
end)
RegisterNetEvent('esx:setJob')
AddEventHandler('esx:setJob', function(job)
	PlayerData.job = job
	
	Citizen.Wait(5000)
	TriggerServerEvent('esx_policejob:forceBlip')
end)

Hope it works!

**Comment by ElPumpo** [comment]
I've pushed an update which should fix this issue, please report back.

**Comment by Oldarorn** [comment]
It doesn't work here even after your update, still no error in F8 or server :)

**Comment by Oldarorn** [comment]
@ElPumpo forget what I said, it's not about you, if the menu doesn't show up it's only because those guys (and me) are using https://github.com/nlmarcio/nb_menuperso it's only a keybinding conflict, I think you can close it :)
