### ISSUE TITLE
Confiscating weapons makes ammo equal 0

### ISSUE THREAD

**Issue by Porcellacion** [ESX-Org/esx_policejob#71]
Hello,

when confiscate e.g a combat-pistol from a player, the ammo goes to zero. 
Even if the player have ammo, it disappears when the weapon is confiscated.

Why is this? Is it the policejob script that's not working as it should or could it be anything else?

Thanks

**Comment by ElPumpo** [comment]
It's a problem with es extended. Previously we had an issue with giving weapons, which duplicated ammo since it wasn't thought about. Now when a weapon is removed all the ammo for the weapon disapears aswell

**Comment by ElPumpo** [comment]
Shouldn't happen any longer with the latest version of ESX. Reciving ammo now adds instead of setting.. needs further testing...

**Comment by ElPumpo** [comment]
Was accually fixed in c341cf32d2459816baadd8e613a568b181637ecf
