### ISSUE TITLE
Not able to see ID

### ISSUE THREAD

**Issue by leffeiilp** [ESX-Org/esx_policejob#73]
I'm trying to see ID or search but nothing will happen. and i don't see anything in the console! :(

**Comment by Parme89** [comment]
Set enableconfiglicenses to FALSE

**Comment by leffeiilp** [comment]
But i'm using esx_license... I want to be able to search, see id and se license's.

**Comment by ElPumpo** [comment]
Give us more information

**Comment by ElPumpo** [comment]
Closing due to lack of information. How on earth are we supposed to help when you don't give any useful information.
