### ISSUE TITLE
Cop blip off duty

### ISSUE THREAD

**Issue by GigaBytesFivem** [ESX-Org/esx_policejob#77]
When you get into the game and change into police uniform the police blips stop working. we tested this one by one and everytime someone changed into uniform they stopped showing on the map.

Anyway to fix this? because its kind of pointless to be in there if thats the way it works.

Also is there any chance of adding a log on and off duty so when officers want to log off and go do drug runs etc they can, they also wont just be earning money from the job while not working.
Thanks

**Comment by tracid56** [comment]
For the drug just remove the condition who's check if it's a police job.

**Comment by HumanTree92** [comment]
On the Subject of when a cop changes uniform i have this happening as well.

**Comment by RedAlex** [comment]
Add in Client/mail.lua
Line 606 (In the menu F6)
```
		elseif data.current.value == 'policeon' then
			jobpolice = "police"
			policegrade = PlayerData.job.grade
						TriggerServerEvent('esx_policejob:setJob', jobpolice, policegrade)
			ESX.UI.Menu.CloseAll()
		elseif data.current.value == 'policeoff' then	
			jobpolice = "policeoff"
			policegrade = PlayerData.job.grade
						TriggerServerEvent('esx_policejob:setJob', jobpolice, policegrade)
			ESX.UI.Menu.CloseAll()

```
And this Line 1921
```
		if IsControlJustReleased(0, Keys['F6']) and not isDead and PlayerData.job ~= nil and PlayerData.job.name == 'policeoff' or and not ESX.UI.Menu.IsOpen('default', GetCurrentResourceName(), 'police_actions') then
			OpenPoliceActionsMenu()
		end	
```	

Add in sql.
```
INSERT INTO `jobs` (name, label) VALUES
	('police','LSPD'),
	('policeoff','Hors Service')
;

INSERT INTO `job_grades` (job_name, grade, name, label, salary, skin_male, skin_female) VALUES
	('police',0,'recruit','Recrue',20,'{}','{}'),
	('police',1,'officer','Officier',40,'{}','{}'),
	('police',2,'sergeant','Sergent',60,'{}','{}'),
	('police',3,'lieutenant','Lieutenant',85,'{}','{}'),
	('police',4,'boss','Commandant',100,'{}','{}'),
	('policeoff',0,'recruit','Recrue',0,'{}','{}'),
	('policeoff',1,'officer','Officier',0,'{}','{}'),
	('policeoff',2,'sergeant','Sergent',0,'{}','{}'),
	('policeoff',3,'lieutenant','Lieutenant',0,'{}','{}'),
	('policeoff',4,'boss','Commandant',0,'{}','{}')
;
```

**Comment by HumanTree92** [comment]
@RedAlex Don't really how i see this to fix the blip issue. All your adding is more jobs.

**Comment by RedAlex** [comment]
This will add a job Off duty, if you ave "police" the blips are ON. if you are "policeoff" the blips are off, you have no sallary. You are realy off duty.
![menupolice](https://user-images.githubusercontent.com/855331/42736883-9522370e-883b-11e8-883d-68b2aa8de8a6.jpg)
