### ISSUE TITLE
Add a Panic Button

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_policejob#78]
So i am seeing many people out there make Panic Buttons but non that work well with Essentialmode. I had seen that you made a Cop Blip so cops can see each other on the map which is amazing. I however do feel like adding in a Panic Button would be amazing. For instance if a cop presses the Panic Button Key &/or types in a command then a Message pops up saying something like Officer Name just pressed his Panic Button near Street Name | Cross Street. All Units respond Code 3. Something like that. 

So far i have seen these scripts that are Panic Buttons just none that work well with Essentialmode.
https://forum.fivem.net/t/release-panic-button-script/55951
https://forum.fivem.net/t/emergency-location-message/55844

**Comment by HumanTree92** [comment]
K after diffing around & doing a few things i was able to get a Panic Button setup. But as a Different Resource. You can check it out here https://github.com/HumanTree92/esx_panicbutton
The way it works is only the Police Job can use the Panic Button but everyone can see it pop up in chat.

**Comment by ElPumpo** [comment]
Sure I can implement it, just take code from the ambulance job distress and implement it here.

**Comment by HumanTree92** [comment]
Closing as i found a fix for this. 
Add this to client/main.lua
```
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)
		if IsControlJustPressed(0, Keys['G']) then
			SendPoliceDistressSignal()
		end
	end
end)

function SendPoliceDistressSignal()
	local playerPed = GetPlayerPed(-1)
	local coords	= GetEntityCoords(playerPed)

	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_phone:send', 'police', _U('police_distress_message'), false, {
		x = coords.x,
		y = coords.y,
		z = coords.z
	})
end
```
Add this to locales/en.lua
```
  ['distress_sent'] = 'distress signal has been sent to available units!',
  ['police_distress_message'] = 'police attention required: OFFICER IN NEED OF ASSISTANCE!',
```
