### ISSUE TITLE
Handcuffed players are able to Right click

### ISSUE THREAD

**Issue by Jeffrey-Lang** [ESX-Org/esx_policejob#87]
Handcuffed players are able to Right click this will break the animation.

I have tried disableing the key but for somereason it wont work

**Comment by Bomlife** [comment]
`DisablePlayerFiring(GetPlayerPed(-1), true)`

**Comment by Jeffrey-Lang** [comment]
@Bomlife tried that but player is still able to right click. it wont aim or go in fighting mode but it will break the animation of the cuffs and player remains then just standing still.

**Comment by ElPumpo** [comment]
How about now?

**Comment by Jeffrey-Lang** [comment]
I will test this and let you know

**Comment by Jeffrey-Lang** [comment]
Still happening, not sure if it is because another mod is overwriting this or something else there are no errors, and like I blocked inventory and that works also pointing with "B" was possible not anymore only thing that breaks the cuffs are aiming

**Comment by HumanTree92** [comment]
I think you might have another script doing this. I had the same problem to i found the problem. I had a script that if i where to put my handsup it would clear all current animations.

**Comment by ElPumpo** [comment]
Jeffery why didn't you then proceed to disable all other scripts to let us know what the hell is going on in your end, your feedback makes my heart skip beats.

**Comment by Jeffrey-Lang** [comment]
I'm sorry my son was sick so didn't have time to do that. Anyways I'm going to test it out and figure out which of my mods is cause this. Because if other user don't have this issue it is clearly on my end. But I do want to let you guys know which mod is causing this so when someone else has the same issue as I do they can find a solution here
