### ISSUE TITLE
Police Garage

### ISSUE THREAD

**Issue by xnubil** [ESX-Org/esx_policejob#94]
Police garage list is duplicating vehicles if you leave the marker, and re open it.   On first open, it shows the 5 cars I have available for my rank. If i leave the marker, and reenter it, it shows the 5 cars twice.  if i do it again, it shows 15 cars (5 cars 3 times) and so on

**Comment by MarioRogue** [comment]
It does it for cars who are not shared and they are for a specific rank, could it get patched please?

**Comment by ElPumpo** [comment]
investigating....
